// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package fwcenter

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_fwcenter_nat_fire_wall", nATFireWallResource)
}

// nATFireWallResource returns the Terraform volcenginecc_fwcenter_nat_fire_wall resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::FWCenter::NATFireWall resource.
func nATFireWallResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AccountId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Account ID for creating the NAT firewall, used to identify the account to which the NAT boundary firewall instance belongs.",
		//	  "type": "string"
		//	}
		"account_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Account ID for creating the NAT firewall, used to identify the account to which the NAT boundary firewall instance belongs.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Bandwidth
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Authorized traffic bandwidth of the NAT boundary firewall instance, measured in Mbps, indicating the maximum network bandwidth allowed for the firewall instance. The minimum value is 10.",
		//	  "format": "int64",
		//	  "minimum": 10,
		//	  "type": "integer"
		//	}
		"bandwidth": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Authorized traffic bandwidth of the NAT boundary firewall instance, measured in Mbps, indicating the maximum network bandwidth allowed for the firewall instance. The minimum value is 10.",
			Required:    true,
			Validators: []validator.Int64{ /*START VALIDATORS*/
				int64validator.AtLeast(10),
			}, /*END VALIDATORS*/
		}, /*END ATTRIBUTE*/
		// Property: CanCreate
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Indicates whether creating a NAT boundary firewall is currently supported. true means supported, false means not supported.",
		//	  "type": "boolean"
		//	}
		"can_create": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Indicates whether creating a NAT boundary firewall is currently supported. true means supported, false means not supported.",
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: CloudFirewallId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Cloud firewall instance ID, used to identify and manage the cloud firewall instance.",
		//	  "type": "string"
		//	}
		"cloud_firewall_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Cloud firewall instance ID, used to identify and manage the cloud firewall instance.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
			// CloudFirewallId is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: ErrMessage
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Error message returned when an error occurs during the creation or query of a NAT boundary firewall instance, used to describe the specific cause of the error.",
		//	  "type": "string"
		//	}
		"err_message": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Error message returned when an error occurs during the creation or query of a NAT boundary firewall instance, used to describe the specific cause of the error.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: FirewallCidr
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Subnet CIDR of the NAT boundary firewall, used to specify the network range protected by the firewall, expressed in CIDR format.",
		//	  "type": "string"
		//	}
		"firewall_cidr": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Subnet CIDR of the NAT boundary firewall, used to specify the network range protected by the firewall, expressed in CIDR format.",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: FirewallStatus
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status of the NAT boundary firewall instance. creating: being created; deleting: being deleted; opened: created; closed: not created; error: error; updating: being upgraded.",
		//	  "enum": [
		//	    "creating",
		//	    "deleting",
		//	    "opened",
		//	    "closed",
		//	    "error",
		//	    "updating"
		//	  ],
		//	  "type": "string"
		//	}
		"firewall_status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Status of the NAT boundary firewall instance. creating: being created; deleting: being deleted; opened: created; closed: not created; error: error; updating: being upgraded.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: NatFirewallId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Unique identifier of the NAT boundary firewall instance.",
		//	  "type": "string"
		//	}
		"nat_firewall_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Unique identifier of the NAT boundary firewall instance.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: NatFirewallName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the NAT boundary firewall instance, used to identify and manage the firewall instance.",
		//	  "type": "string"
		//	}
		"nat_firewall_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the NAT boundary firewall instance, used to identify and manage the firewall instance.",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: NatFirewallSubnetCidr
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Subnet CIDR of the NAT boundary firewall instance, used to identify the subnet IP address range protected by the firewall instance.",
		//	  "type": "string"
		//	}
		"nat_firewall_subnet_cidr": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Subnet CIDR of the NAT boundary firewall instance, used to identify the subnet IP address range protected by the firewall instance.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: NatGatewayId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "NAT gateway instance ID, used to identify and manage the NAT gateway instance. You must specify the associated NAT gateway when creating a NAT firewall.",
		//	  "type": "string"
		//	}
		"nat_gateway_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "NAT gateway instance ID, used to identify and manage the NAT gateway instance. You must specify the associated NAT gateway when creating a NAT firewall.",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: NatGatewayName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the NAT gateway, used to identify the associated NAT gateway.",
		//	  "type": "string"
		//	}
		"nat_gateway_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the NAT gateway, used to identify the associated NAT gateway.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: PeakTrafficWithin7Day
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Peak traffic of the NAT boundary firewall instance in the past 7 days, measured in bps, used to monitor the highest network traffic usage.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"peak_traffic_within_7_day": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Peak traffic of the NAT boundary firewall instance in the past 7 days, measured in bps, used to monitor the highest network traffic usage.",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Project name, used to identify and manage the project to which the resource belongs. The default value is default.",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Project name, used to identify and manage the project to which the resource belongs. The default value is default.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ProjectNameForNatGate
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Project name to which the associated NAT gateway belongs.",
		//	  "type": "string"
		//	}
		"project_name_for_nat_gate": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Project name to which the associated NAT gateway belongs.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: VpcCidr
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Subnet CIDR of the associated VPC, used to identify the IP address range of the VPC.",
		//	  "type": "string"
		//	}
		"vpc_cidr": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Subnet CIDR of the associated VPC, used to identify the IP address range of the VPC.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: VpcId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Unique identifier of the associated VPC.",
		//	  "type": "string"
		//	}
		"vpc_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Unique identifier of the associated VPC.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: VpcName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the associated VPC.",
		//	  "type": "string"
		//	}
		"vpc_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the associated VPC.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ZoneId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Availability zone where the NAT boundary firewall instance is located, used to identify the specific physical area where the instance is deployed.",
		//	  "type": "string"
		//	}
		"zone_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Availability zone where the NAT boundary firewall instance is located, used to identify the specific physical area where the instance is deployed.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "NAT boundary firewall instance. Provides security protection and access control for north-south traffic passing through the NAT gateway.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::FWCenter::NATFireWall").WithTerraformTypeName("volcenginecc_fwcenter_nat_fire_wall")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"account_id":                "AccountId",
		"bandwidth":                 "Bandwidth",
		"can_create":                "CanCreate",
		"cloud_firewall_id":         "CloudFirewallId",
		"err_message":               "ErrMessage",
		"firewall_cidr":             "FirewallCidr",
		"firewall_status":           "FirewallStatus",
		"nat_firewall_id":           "NatFirewallId",
		"nat_firewall_name":         "NatFirewallName",
		"nat_firewall_subnet_cidr":  "NatFirewallSubnetCidr",
		"nat_gateway_id":            "NatGatewayId",
		"nat_gateway_name":          "NatGatewayName",
		"peak_traffic_within_7_day": "PeakTrafficWithin7Day",
		"project_name":              "ProjectName",
		"project_name_for_nat_gate": "ProjectNameForNatGate",
		"vpc_cidr":                  "VpcCidr",
		"vpc_id":                    "VpcId",
		"vpc_name":                  "VpcName",
		"zone_id":                   "ZoneId",
	})

	opts = opts.WithWriteOnlyPropertyPaths([]string{
		"/properties/CloudFirewallId",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/NatFirewallId",
		"/properties/AccountId",
		"/properties/FirewallStatus",
		"/properties/CanCreate",
		"/properties/ErrMessage",
		"/properties/NatFirewallSubnetCidr",
		"/properties/NatGatewayName",
		"/properties/PeakTrafficWithin7Day",
		"/properties/ProjectNameForNatGate",
		"/properties/VpcCidr",
		"/properties/VpcId",
		"/properties/VpcName",
		"/properties/ZoneId",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/NatGatewayId",
		"/properties/FirewallCidr",
		"/properties/CloudFirewallId",
		"/properties/ProjectName",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
