// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package fwcenter

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_fwcenter_nat_fire_wall_control_policy", natFireWallControlPolicyDataSource)
}

// natFireWallControlPolicyDataSource returns the Terraform volcenginecc_fwcenter_nat_fire_wall_control_policy data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::FWCenter::NatFireWallControlPolicy resource.
func natFireWallControlPolicyDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AccountId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "User's unique identifier ID.",
		//	  "type": "string"
		//	}
		"account_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "User's unique identifier ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Action
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Policy action. accept: allow; deny: deny; monitor: observe.",
		//	  "enum": [
		//	    "accept",
		//	    "deny",
		//	    "monitor"
		//	  ],
		//	  "type": "string"
		//	}
		"action": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Policy action. accept: allow; deny: deny; monitor: observe.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Description of the policy.",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Description of the policy.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DestPort
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination port, either a single port or a port range (e.g., 22/22, 100/200). If DestPortType is group, provide a list of port address book UUIDs, separated by commas. Leave blank if the protocol is ICMP or ANY.",
		//	  "type": "string"
		//	}
		"dest_port": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Destination port, either a single port or a port range (e.g., 22/22, 100/200). If DestPortType is group, provide a list of port address book UUIDs, separated by commas. Leave blank if the protocol is ICMP or ANY.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DestPortGroupType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination port book type.",
		//	  "type": "string"
		//	}
		"dest_port_group_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Destination port book type.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DestPortList
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination port list.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"dest_port_list": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "Destination port list.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DestPortListV1
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination port list (structured).",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Structured address entry.",
		//	    "properties": {
		//	      "Address": {
		//	        "description": "Specific address information.",
		//	        "type": "string"
		//	      },
		//	      "Description": {
		//	        "description": "Description.",
		//	        "type": "string"
		//	      },
		//	      "Type": {
		//	        "description": "Address type. ip: IPv4; ipv6: IPv6; domain: domain name; port: port.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"dest_port_list_v1": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Address
					"address": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Specific address information.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Description
					"description": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Description.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Type
					"type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Address type. ip: IPv4; ipv6: IPv6; domain: domain name; port: port.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Destination port list (structured).",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DestPortType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination port type. port: port; group: port address book.",
		//	  "type": "string"
		//	}
		"dest_port_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Destination port type. port: port; group: port address book.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Destination
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination address. The value depends on DestinationType: if net, use the destination CIDR address; if group, use the destination address book UUID. Separate multiple address books with commas.",
		//	  "type": "string"
		//	}
		"destination": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Destination address. The value depends on DestinationType: if net, use the destination CIDR address; if group, use the destination address book UUID. Separate multiple address books with commas.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DestinationCidrList
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination CIDR list.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"destination_cidr_list": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "Destination CIDR list.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DestinationCidrListV1
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination CIDR list (structured).",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Structured address entry.",
		//	    "properties": {
		//	      "Address": {
		//	        "description": "Specific address information.",
		//	        "type": "string"
		//	      },
		//	      "Description": {
		//	        "description": "Description.",
		//	        "type": "string"
		//	      },
		//	      "Type": {
		//	        "description": "Address type. ip: IPv4; ipv6: IPv6; domain: domain name; port: port.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"destination_cidr_list_v1": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Address
					"address": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Specific address information.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Description
					"description": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Description.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Type
					"type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Address type. ip: IPv4; ipv6: IPv6; domain: domain name; port: port.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Destination CIDR list (structured).",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DestinationDomainList
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination domain name list.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"destination_domain_list": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "Destination domain name list.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DestinationGroupType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination address book type.",
		//	  "type": "string"
		//	}
		"destination_group_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Destination address book type.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DestinationType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination address type, used to specify the format and source of the destination address in the access control policy. net: destination network segment (CIDR format); group: destination address book (UUID format).",
		//	  "enum": [
		//	    "net",
		//	    "group"
		//	  ],
		//	  "type": "string"
		//	}
		"destination_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Destination address type, used to specify the format and source of the destination address in the access control policy. net: destination network segment (CIDR format); group: destination address book (UUID format).",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Direction
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Policy direction, used to specify the traffic direction for the access control policy. in: inbound; out: outbound.",
		//	  "enum": [
		//	    "in",
		//	    "out"
		//	  ],
		//	  "type": "string"
		//	}
		"direction": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Policy direction, used to specify the traffic direction for the access control policy. in: inbound; out: outbound.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: EffectStatus
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status of the access control policy. Values: 1: Inactive; 2: Deploying; 3: Active.",
		//	  "type": "integer"
		//	}
		"effect_status": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Status of the access control policy. Values: 1: Inactive; 2: Deploying; 3: Active.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: EndTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Policy end timestamp. This field is not required when RepeatType is Permanent. When RepeatType is Once, Daily, Weekly, or Monthly, this field must be provided.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"end_time": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Policy end timestamp. This field is not required when RepeatType is Permanent. When RepeatType is Once, Daily, Weekly, or Monthly, this field must be provided.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HitCnt
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Hit count, indicating the number of times this policy has been triggered.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"hit_cnt": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Hit count, indicating the number of times this policy has been triggered.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: IsEffected
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Whether the policy is effective.",
		//	  "type": "boolean"
		//	}
		"is_effected": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Whether the policy is effective.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: LastHitTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Last hit timestamp, indicating the last time this policy was triggered.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"last_hit_time": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Last hit timestamp, indicating the last time this policy was triggered.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: NatFirewallId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "NAT border firewall instance ID.",
		//	  "type": "string"
		//	}
		"nat_firewall_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "NAT border firewall instance ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Prio
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Policy priority. A lower value indicates a higher priority. By default, the priority is set to the highest. 0: lowest priority; 1: highest priority. When modifying, the minimum value for this parameter is 1.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"prio": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Policy priority. A lower value indicates a higher priority. By default, the priority is set to the highest. 0: lowest priority; 1: highest priority. When modifying, the minimum value for this parameter is 1.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Proto
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Protocol type. ICMP: ICMP protocol; TCP: TCP protocol; UDP: UDP protocol; ANY: any protocol.",
		//	  "enum": [
		//	    "ICMP",
		//	    "TCP",
		//	    "UDP",
		//	    "ANY"
		//	  ],
		//	  "type": "string"
		//	}
		"proto": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Protocol type. ICMP: ICMP protocol; TCP: TCP protocol; UDP: UDP protocol; ANY: any protocol.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: RepeatDays
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Repeat cycle. This field is not required when RepeatType is Daily. When RepeatType is Weekly, the value range is [0, 6], corresponding to Sunday through Saturday. When RepeatType is Monthly, the value range is [1, 31], corresponding to the days of the month.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "integer"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"repeat_days": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.Int64Type,
			Description: "Repeat cycle. This field is not required when RepeatType is Daily. When RepeatType is Weekly, the value range is [0, 6], corresponding to Sunday through Saturday. When RepeatType is Monthly, the value range is [1, 31], corresponding to the days of the month.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: RepeatEndTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Repeat end time. This field is required when RepeatType is Daily, Weekly, or Monthly. Accurate to the minute, format: hh:mm.",
		//	  "type": "string"
		//	}
		"repeat_end_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Repeat end time. This field is required when RepeatType is Daily, Weekly, or Monthly. Accurate to the minute, format: hh:mm.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: RepeatStartTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Repeat start time. This field is required when RepeatType is Daily, Weekly, or Monthly. Accurate to the minute, format: hh:mm.",
		//	  "type": "string"
		//	}
		"repeat_start_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Repeat start time. This field is required when RepeatType is Daily, Weekly, or Monthly. Accurate to the minute, format: hh:mm.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: RepeatType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Policy repeat type. Permanent: always effective; Once: effective only once; Daily: effective every day; Weekly: effective every week; Monthly: effective every month.",
		//	  "enum": [
		//	    "Permanent",
		//	    "Once",
		//	    "Daily",
		//	    "Weekly",
		//	    "Monthly"
		//	  ],
		//	  "type": "string"
		//	}
		"repeat_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Policy repeat type. Permanent: always effective; Once: effective only once; Daily: effective every day; Weekly: effective every week; Monthly: effective every month.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: RuleId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Unique ID of the access control policy.",
		//	  "type": "string"
		//	}
		"rule_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Unique ID of the access control policy.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Source
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Source address. The format varies based on the value of SourceType. If SourceType is net, use a CIDR address; if SourceType is group, use the UUID of the source address book; if SourceType is location, use the region code.",
		//	  "type": "string"
		//	}
		"source": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Source address. The format varies based on the value of SourceType. If SourceType is net, use a CIDR address; if SourceType is group, use the UUID of the source address book; if SourceType is location, use the region code.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SourceCidrList
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Source CIDR list.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"source_cidr_list": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "Source CIDR list.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SourceCidrListV1
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Source CIDR list (structured).",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Structured address entry.",
		//	    "properties": {
		//	      "Address": {
		//	        "description": "Specific address information.",
		//	        "type": "string"
		//	      },
		//	      "Description": {
		//	        "description": "Description.",
		//	        "type": "string"
		//	      },
		//	      "Type": {
		//	        "description": "Address type. ip: IPv4; ipv6: IPv6; domain: domain name; port: port.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"source_cidr_list_v1": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Address
					"address": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Specific address information.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Description
					"description": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Description.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Type
					"type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Address type. ip: IPv4; ipv6: IPv6; domain: domain name; port: port.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Source CIDR list (structured).",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SourceGroupType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Source address book type.",
		//	  "type": "string"
		//	}
		"source_group_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Source address book type.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SourceType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Source address type, used to specify the format and source of the source address in the access control policy. net: source network segment (CIDR format); group: source address book (UUID format); location: source region (region code format).",
		//	  "enum": [
		//	    "net",
		//	    "location",
		//	    "group"
		//	  ],
		//	  "type": "string"
		//	}
		"source_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Source address type, used to specify the format and source of the source address in the access control policy. net: source network segment (CIDR format); group: source address book (UUID format); location: source region (region code format).",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: StartTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Policy start timestamp. This field is not required when RepeatType is Permanent. When RepeatType is Once, Daily, Weekly, or Monthly, this field must be provided.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"start_time": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Policy start timestamp. This field is not required when RepeatType is Permanent. When RepeatType is Once, Daily, Weekly, or Monthly, this field must be provided.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Policy switch status. false: off; true: on.",
		//	  "type": "boolean"
		//	}
		"status": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Policy switch status. false: off; true: on.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Policy update timestamp.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"update_time": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Policy update timestamp.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UseCount
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Number of policies occupied by this policy.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"use_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Number of policies occupied by this policy.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::FWCenter::NatFireWallControlPolicy",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::FWCenter::NatFireWallControlPolicy").WithTerraformTypeName("volcenginecc_fwcenter_nat_fire_wall_control_policy")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"account_id":               "AccountId",
		"action":                   "Action",
		"address":                  "Address",
		"description":              "Description",
		"dest_port":                "DestPort",
		"dest_port_group_type":     "DestPortGroupType",
		"dest_port_list":           "DestPortList",
		"dest_port_list_v1":        "DestPortListV1",
		"dest_port_type":           "DestPortType",
		"destination":              "Destination",
		"destination_cidr_list":    "DestinationCidrList",
		"destination_cidr_list_v1": "DestinationCidrListV1",
		"destination_domain_list":  "DestinationDomainList",
		"destination_group_type":   "DestinationGroupType",
		"destination_type":         "DestinationType",
		"direction":                "Direction",
		"effect_status":            "EffectStatus",
		"end_time":                 "EndTime",
		"hit_cnt":                  "HitCnt",
		"is_effected":              "IsEffected",
		"last_hit_time":            "LastHitTime",
		"nat_firewall_id":          "NatFirewallId",
		"prio":                     "Prio",
		"proto":                    "Proto",
		"repeat_days":              "RepeatDays",
		"repeat_end_time":          "RepeatEndTime",
		"repeat_start_time":        "RepeatStartTime",
		"repeat_type":              "RepeatType",
		"rule_id":                  "RuleId",
		"source":                   "Source",
		"source_cidr_list":         "SourceCidrList",
		"source_cidr_list_v1":      "SourceCidrListV1",
		"source_group_type":        "SourceGroupType",
		"source_type":              "SourceType",
		"start_time":               "StartTime",
		"status":                   "Status",
		"type":                     "Type",
		"update_time":              "UpdateTime",
		"use_count":                "UseCount",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
