// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package config

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_config_configuration_recorder", configurationRecorderResource)
}

// configurationRecorderResource returns the Terraform volcenginecc_config_configuration_recorder resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::Config::ConfigurationRecorder resource.
func configurationRecorderResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: ConfigurationRecorderStatus
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Configuration recorder status. Options: Disabled, PendingEnable, Building, Rebuilding, Enabled, PendingDisable",
		//	  "type": "string"
		//	}
		"configuration_recorder_status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Configuration recorder status. Options: Disabled, PendingEnable, Building, Rebuilding, Enabled, PendingDisable",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: CreateBy
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Configuration recorder creation source",
		//	  "type": "string"
		//	}
		"create_by": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Configuration recorder creation source",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: IncludeAllResourceTypes
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Whether to record all supported resource types",
		//	  "type": "boolean"
		//	}
		"include_all_resource_types": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Whether to record all supported resource types",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: IncludeResourceTypes
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "List of specified resource types to record",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"include_resource_types": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "List of specified resource types to record",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: RecorderId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Configuration recorder ID",
		//	  "type": "string"
		//	}
		"recorder_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Configuration recorder ID",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: RecorderName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Configuration recorder name",
		//	  "type": "string"
		//	}
		"recorder_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Configuration recorder name",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: RecorderType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Configuration recorder type. Options: SingleAccount, Organization",
		//	  "type": "string"
		//	}
		"recorder_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Configuration recorder type. Options: SingleAccount, Organization",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Configuration Recorder is used to record and track configuration changes for specified resource types under the Volcano Engine account",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::Config::ConfigurationRecorder").WithTerraformTypeName("volcenginecc_config_configuration_recorder")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"configuration_recorder_status": "ConfigurationRecorderStatus",
		"create_by":                     "CreateBy",
		"include_all_resource_types":    "IncludeAllResourceTypes",
		"include_resource_types":        "IncludeResourceTypes",
		"recorder_id":                   "RecorderId",
		"recorder_name":                 "RecorderName",
		"recorder_type":                 "RecorderType",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/ConfigurationRecorderStatus",
		"/properties/CreateBy",
		"/properties/RecorderId",
		"/properties/RecorderName",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/RecorderType",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
