// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package rdsmysql

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_rdsmysql_ssl", sslDataSource)
}

// sslDataSource returns the Terraform volcenginecc_rdsmysql_ssl data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::RDSMySQL::Ssl resource.
func sslDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: Address
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Protected address.",
		//	  "type": "string"
		//	}
		"address": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Protected address.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: InstanceId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance ID.",
		//	  "type": "string"
		//	}
		"instance_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Instance ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: IsValid
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Certificate validity. Values:\n\n- `true`: Valid\n- `false`: Invalid",
		//	  "type": "boolean"
		//	}
		"is_valid": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Certificate validity. Values:\n  \n    - `true`: Valid\n    - `false`: Invalid",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ReloadSSLCertificate
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Update SSL certificate validity period. Set to `true` to update the SSL certificate validity period. Takes effect only when SSL encryption is enabled for the instance, and cannot be modified together with the SSLEnable field.",
		//	  "type": "boolean"
		//	}
		"reload_ssl_certificate": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Update SSL certificate validity period. Set to `true` to update the SSL certificate validity period. Takes effect only when SSL encryption is enabled for the instance, and cannot be modified together with the SSLEnable field.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SSLEnable
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "SSL switch. Values:\n\n- `true`: Enabled\n- `false`: Disabled",
		//	  "type": "boolean"
		//	}
		"ssl_enable": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "SSL switch. Values:\n  \n    - `true`: Enabled\n    - `false`: Disabled",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SSLExpireTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Certificate expiration time. Format: `yyyy-MM-dd HH:mm:ss` (UTC time).",
		//	  "type": "string"
		//	}
		"ssl_expire_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Certificate expiration time. Format: `yyyy-MM-dd HH:mm:ss` (UTC time).",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TLSVersion
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Supported TLS versions. Separate multiple versions with commas (,).",
		//	  "type": "string"
		//	}
		"tls_version": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Supported TLS versions. Separate multiple versions with commas (,).",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::RDSMySQL::Ssl",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::RDSMySQL::Ssl").WithTerraformTypeName("volcenginecc_rdsmysql_ssl")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"address":                "Address",
		"instance_id":            "InstanceId",
		"is_valid":               "IsValid",
		"reload_ssl_certificate": "ReloadSSLCertificate",
		"ssl_enable":             "SSLEnable",
		"ssl_expire_time":        "SSLExpireTime",
		"tls_version":            "TLSVersion",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
