// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package rdsmysql

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_rdsmysql_ssl", sslResource)
}

// sslResource returns the Terraform volcenginecc_rdsmysql_ssl resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::RDSMySQL::Ssl resource.
func sslResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: Address
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Protected address.",
		//	  "type": "string"
		//	}
		"address": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Protected address.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: InstanceId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance ID.",
		//	  "type": "string"
		//	}
		"instance_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Instance ID.",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: IsValid
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Certificate validity. Values:\n\n- `true`: Valid\n- `false`: Invalid",
		//	  "type": "boolean"
		//	}
		"is_valid": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Certificate validity. Values:\n  \n    - `true`: Valid\n    - `false`: Invalid",
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ReloadSSLCertificate
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Update SSL certificate validity period. Set to `true` to update the SSL certificate validity period. Takes effect only when SSL encryption is enabled for the instance, and cannot be modified together with the SSLEnable field.",
		//	  "type": "boolean"
		//	}
		"reload_ssl_certificate": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Update SSL certificate validity period. Set to `true` to update the SSL certificate validity period. Takes effect only when SSL encryption is enabled for the instance, and cannot be modified together with the SSLEnable field.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
			// ReloadSSLCertificate is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: SSLEnable
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "SSL switch. Values:\n\n- `true`: Enabled\n- `false`: Disabled",
		//	  "type": "boolean"
		//	}
		"ssl_enable": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "SSL switch. Values:\n  \n    - `true`: Enabled\n    - `false`: Disabled",
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SSLExpireTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Certificate expiration time. Format: `yyyy-MM-dd HH:mm:ss` (UTC time).",
		//	  "type": "string"
		//	}
		"ssl_expire_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Certificate expiration time. Format: `yyyy-MM-dd HH:mm:ss` (UTC time).",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TLSVersion
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Supported TLS versions. Separate multiple versions with commas (,).",
		//	  "type": "string"
		//	}
		"tls_version": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Supported TLS versions. Separate multiple versions with commas (,).",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "SSL encryption configuration for Volcano Engine RDS MySQL instances. Use ModifyDBInstanceSSL to enable, disable, or adjust the instance's SSL settings, and use DescribeDBInstanceSSL to query the current SSL status.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::RDSMySQL::Ssl").WithTerraformTypeName("volcenginecc_rdsmysql_ssl")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"address":                "Address",
		"instance_id":            "InstanceId",
		"is_valid":               "IsValid",
		"reload_ssl_certificate": "ReloadSSLCertificate",
		"ssl_enable":             "SSLEnable",
		"ssl_expire_time":        "SSLExpireTime",
		"tls_version":            "TLSVersion",
	})

	opts = opts.WithWriteOnlyPropertyPaths([]string{
		"/properties/ReloadSSLCertificate",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/IsValid",
		"/properties/SSLExpireTime",
		"/properties/SSLEnable",
		"/properties/TLSVersion",
		"/properties/Address",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/InstanceId",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
