// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package id

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
	fwvalidators "github.com/volcengine/terraform-provider-volcenginecc/internal/validators"
)

func init() {
	registry.AddResourceFactory("volcenginecc_id_auth_config", authConfigResource)
}

// authConfigResource returns the Terraform volcenginecc_id_auth_config resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::ID::AuthConfig resource.
func authConfigResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: ApiKeyAuthConfigs
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ApiKey Authentication Configuration",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "ApiKey Authentication Configuration",
		//	    "properties": {
		//	      "ApiKey": {
		//	        "description": "ApiKey Value",
		//	        "type": "string"
		//	      },
		//	      "ApiKeyMetadata": {
		//	        "description": "ApiKey Metadata",
		//	        "insertionOrder": false,
		//	        "items": {
		//	          "description": "ApiKey Metadata Item",
		//	          "properties": {
		//	            "Location": {
		//	              "description": "Parameter Location",
		//	              "type": "string"
		//	            },
		//	            "ParameterName": {
		//	              "description": "Parameter Name",
		//	              "type": "string"
		//	            }
		//	          },
		//	          "required": [
		//	            "Location",
		//	            "ParameterName"
		//	          ],
		//	          "type": "object"
		//	        },
		//	        "type": "array",
		//	        "uniqueItems": true
		//	      },
		//	      "ApiKeyName": {
		//	        "description": "ApiKey Name",
		//	        "type": "string"
		//	      },
		//	      "ExpiryTimestamp": {
		//	        "description": "Expiration Timestamp",
		//	        "format": "int64",
		//	        "type": "integer"
		//	      }
		//	    },
		//	    "required": [
		//	      "ApiKeyName"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"api_key_auth_configs": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: ApiKey
					"api_key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "ApiKey Value",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: ApiKeyMetadata
					"api_key_metadata": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
						NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
							Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
								// Property: Location
								"location": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Parameter Location",
									Optional:    true,
									Computed:    true,
									Validators: []validator.String{ /*START VALIDATORS*/
										fwvalidators.NotNullString(),
									}, /*END VALIDATORS*/
									PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
										stringplanmodifier.UseStateForUnknown(),
									}, /*END PLAN MODIFIERS*/
								}, /*END ATTRIBUTE*/
								// Property: ParameterName
								"parameter_name": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Parameter Name",
									Optional:    true,
									Computed:    true,
									Validators: []validator.String{ /*START VALIDATORS*/
										fwvalidators.NotNullString(),
									}, /*END VALIDATORS*/
									PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
										stringplanmodifier.UseStateForUnknown(),
									}, /*END PLAN MODIFIERS*/
								}, /*END ATTRIBUTE*/
							}, /*END SCHEMA*/
						}, /*END NESTED OBJECT*/
						Description: "ApiKey Metadata\n Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
							setplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: ApiKeyName
					"api_key_name": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "ApiKey Name",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{ /*START VALIDATORS*/
							fwvalidators.NotNullString(),
						}, /*END VALIDATORS*/
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: ExpiryTimestamp
					"expiry_timestamp": schema.Int64Attribute{ /*START ATTRIBUTE*/
						Description: "Expiration Timestamp",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
							int64planmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "ApiKey Authentication Configuration\n Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: AuthType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Authentication Type. Only Jwt or ApiKey is allowed",
		//	  "enum": [
		//	    "Jwt",
		//	    "ApiKey"
		//	  ],
		//	  "type": "string"
		//	}
		"auth_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Authentication Type. Only Jwt or ApiKey is allowed",
			Required:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.OneOf(
					"Jwt",
					"ApiKey",
				),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ConfigName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Configuration Name",
		//	  "type": "string"
		//	}
		"config_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Configuration Name",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: CreatedAt
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation Time",
		//	  "type": "string"
		//	}
		"created_at": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation Time",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Configuration Description",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Configuration Description",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: InboundAuthConfigId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Inbound Authentication Configuration ID",
		//	  "type": "string"
		//	}
		"inbound_auth_config_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Inbound Authentication Configuration ID",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: InstanceId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Bound Instance ID",
		//	  "type": "string"
		//	}
		"instance_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Bound Instance ID",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: JwtAuthConfig
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "JWT Authentication Configuration",
		//	  "properties": {
		//	    "AllowedAudiences": {
		//	      "description": "Allowed Audience List",
		//	      "insertionOrder": false,
		//	      "items": {
		//	        "type": "string"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    },
		//	    "AllowedClients": {
		//	      "description": "Allowed Client List",
		//	      "insertionOrder": false,
		//	      "items": {
		//	        "type": "string"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    },
		//	    "DiscoveryUrl": {
		//	      "description": "JWT Discovery URL。",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "required": [
		//	    "DiscoveryUrl"
		//	  ],
		//	  "type": "object"
		//	}
		"jwt_auth_config": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: AllowedAudiences
				"allowed_audiences": schema.SetAttribute{ /*START ATTRIBUTE*/
					ElementType: types.StringType,
					Description: "Allowed Audience List",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
						setplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: AllowedClients
				"allowed_clients": schema.SetAttribute{ /*START ATTRIBUTE*/
					ElementType: types.StringType,
					Description: "Allowed Client List",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
						setplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: DiscoveryUrl
				"discovery_url": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "JWT Discovery URL。",
					Optional:    true,
					Computed:    true,
					Validators: []validator.String{ /*START VALIDATORS*/
						fwvalidators.NotNullString(),
					}, /*END VALIDATORS*/
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "JWT Authentication Configuration",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
				objectplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Trn
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Resource TRN",
		//	  "type": "string"
		//	}
		"trn": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Resource TRN",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: UpdatedAt
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Update Time",
		//	  "type": "string"
		//	}
		"updated_at": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Update Time",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Inbound Authentication Configuration",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::ID::AuthConfig").WithTerraformTypeName("volcenginecc_id_auth_config")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"allowed_audiences":      "AllowedAudiences",
		"allowed_clients":        "AllowedClients",
		"api_key":                "ApiKey",
		"api_key_auth_configs":   "ApiKeyAuthConfigs",
		"api_key_metadata":       "ApiKeyMetadata",
		"api_key_name":           "ApiKeyName",
		"auth_type":              "AuthType",
		"config_name":            "ConfigName",
		"created_at":             "CreatedAt",
		"description":            "Description",
		"discovery_url":          "DiscoveryUrl",
		"expiry_timestamp":       "ExpiryTimestamp",
		"inbound_auth_config_id": "InboundAuthConfigId",
		"instance_id":            "InstanceId",
		"jwt_auth_config":        "JwtAuthConfig",
		"location":               "Location",
		"parameter_name":         "ParameterName",
		"trn":                    "Trn",
		"updated_at":             "UpdatedAt",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/InboundAuthConfigId",
		"/properties/Trn",
		"/properties/CreatedAt",
		"/properties/UpdatedAt",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/ConfigName",
		"/properties/AuthType",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
