// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/plural-data-source/main.go; DO NOT EDIT.

package id_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/acctest"
)

func TestAccVolcengineIDOauth2CredentialProvidersDataSource_basic(t *testing.T) {
	td := acctest.NewTestData(t, "Volcengine::ID::Oauth2CredentialProvider", "volcenginecc_id_oauth2_credential_providers", "test")

	td.DataSourceTest(t, []resource.TestStep{
		{
			Config: td.EmptyDataSourceConfig(),
			Check: resource.ComposeTestCheckFunc(
				resource.TestCheckResourceAttrSet(fmt.Sprintf("data.%s", td.ResourceName), "ids.#"),
			),
		},
	})
}
