// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package id

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_id_permission_namespace", permissionNamespaceDataSource)
}

// permissionNamespaceDataSource returns the Terraform volcenginecc_id_permission_namespace data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::ID::PermissionNamespace resource.
func permissionNamespaceDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: Associates
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Associated Entities List",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"associates": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "Associated Entities List",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CreateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Namespace Creation Time",
		//	  "type": "string"
		//	}
		"create_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Namespace Creation Time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Namespace Description",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Namespace Description",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: NamespaceId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Namespace Unique ID",
		//	  "type": "string"
		//	}
		"namespace_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Namespace Unique ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: NamespaceName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Namespace Name",
		//	  "type": "string"
		//	}
		"namespace_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Namespace Name",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Project Associated with Namespace",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Project Associated with Namespace",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Namespace Tag List",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Tag Key-Value Pair",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Tag Key",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Tag Value",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag Key",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag Value",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Namespace Tag List",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Trn
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Namespace TRN",
		//	  "type": "string"
		//	}
		"trn": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Namespace TRN",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Namespace Update Time",
		//	  "type": "string"
		//	}
		"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Namespace Update Time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::ID::PermissionNamespace",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::ID::PermissionNamespace").WithTerraformTypeName("volcenginecc_id_permission_namespace")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"associates":     "Associates",
		"create_time":    "CreateTime",
		"description":    "Description",
		"key":            "Key",
		"namespace_id":   "NamespaceId",
		"namespace_name": "NamespaceName",
		"project_name":   "ProjectName",
		"tags":           "Tags",
		"trn":            "Trn",
		"update_time":    "UpdateTime",
		"value":          "Value",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
