// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package kms

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_kms_key_material", keyMaterialResource)
}

// keyMaterialResource returns the Terraform volcenginecc_kms_key_material resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::KMS::KeyMaterial resource.
func keyMaterialResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: EncryptedKeyMaterial
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "The key material obtained after the user encrypts using the import public key, encoded in Base64; this value is passed directly to the ImportKeyMaterial interface.",
		//	  "maxLength": 8192,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"encrypted_key_material": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "The key material obtained after the user encrypts using the import public key, encoded in Base64; this value is passed directly to the ImportKeyMaterial interface.",
			Required:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthBetween(1, 8192),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
			// EncryptedKeyMaterial is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: ExpirationModel
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Key material expiration type. Values: KEY_MATERIAL_DOES_NOT_EXPIRE (default), KEY_MATERIAL_EXPIRES.",
		//	  "type": "string"
		//	}
		"expiration_model": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Key material expiration type. Values: KEY_MATERIAL_DOES_NOT_EXPIRE (default), KEY_MATERIAL_EXPIRES.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
			// ExpirationModel is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: ImportToken
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "The import token obtained after the user calls the interface to retrieve import parameters; this value is passed directly to the ImportKeyMaterial interface.",
		//	  "type": "string"
		//	}
		"import_token": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "The import token obtained after the user calls the interface to retrieve import parameters; this value is passed directly to the ImportKeyMaterial interface.",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
			// ImportToken is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: KeyID
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Unique identifier of the target master key in UUID format; the Origin of this key must be External.",
		//	  "type": "string"
		//	}
		"key_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Unique identifier of the target master key in UUID format; the Origin of this key must be External.",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: KeyMaterialExpireTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "The expiration time of the key material recorded by the server after import; if the material does not expire, this field is an empty string.",
		//	  "type": "string"
		//	}
		"key_material_expire_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "The expiration time of the key material recorded by the server after import; if the material does not expire, this field is an empty string.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: KeyState
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Current status of the target master key. Values: Enable, Disable, PendingDelete, Archived, PendingImport, PendingReplicaDelete.",
		//	  "type": "string"
		//	}
		"key_state": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Current status of the target master key. Values: Enable, Disable, PendingDelete, Archived, PendingImport, PendingReplicaDelete.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Origin
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Source of the target master key. Values: CloudKMS, External, ExternalKeyStore. The KeyMaterial resource is only valid for keys with External origin.",
		//	  "type": "string"
		//	}
		"origin": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Source of the target master key. Values: CloudKMS, External, ExternalKeyStore. The KeyMaterial resource is only valid for keys with External origin.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ValidTo
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Key material expiration time, Unix timestamp in seconds; required when the ExpirationModel parameter is set to KEY_MATERIAL_EXPIRES. Must be a time after the current moment, based on server time.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"valid_to": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Key material expiration time, Unix timestamp in seconds; required when the ExpirationModel parameter is set to KEY_MATERIAL_EXPIRES. Must be a time after the current moment, based on server time.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
				int64planmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
			// ValidTo is a write-only property.
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Key Management Service (KMS) key material resource. Used to import user-provided (BYOK) encrypted key material into a specified master key with Origin=External. Users must obtain import parameters, encrypt the key material, and provide EncryptedKeyMaterial and ImportToken to the resource. The Provider then calls ImportKeyMaterial to complete the import.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::KMS::KeyMaterial").WithTerraformTypeName("volcenginecc_kms_key_material")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"encrypted_key_material":   "EncryptedKeyMaterial",
		"expiration_model":         "ExpirationModel",
		"import_token":             "ImportToken",
		"key_id":                   "KeyID",
		"key_material_expire_time": "KeyMaterialExpireTime",
		"key_state":                "KeyState",
		"origin":                   "Origin",
		"valid_to":                 "ValidTo",
	})

	opts = opts.IsImmutableType(true)

	opts = opts.WithWriteOnlyPropertyPaths([]string{
		"/properties/ExpirationModel",
		"/properties/EncryptedKeyMaterial",
		"/properties/ImportToken",
		"/properties/ValidTo",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/KeyMaterialExpireTime",
		"/properties/KeyState",
		"/properties/Origin",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/KeyID",
		"/properties/EncryptedKeyMaterial",
		"/properties/ImportToken",
		"/properties/ExpirationModel",
		"/properties/ValidTo",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
