// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package kms

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_kms_secret", secretDataSource)
}

// secretDataSource returns the Terraform volcenginecc_kms_secret data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::KMS::Secret resource.
func secretDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AutomaticRotation
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Whether to enable automatic rotation. Applies only to credentials of type IAM|RDS|Redis|ECS",
		//	  "type": "boolean"
		//	}
		"automatic_rotation": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Whether to enable automatic rotation. Applies only to credentials of type IAM|RDS|Redis|ECS",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CancelSecretDeletion
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Trigger: When set to true, calls the KMS CancelSecretDeletion API to cancel the scheduled deletion of the credential.",
		//	  "type": "boolean"
		//	}
		"cancel_secret_deletion": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Trigger: When set to true, calls the KMS CancelSecretDeletion API to cancel the scheduled deletion of the credential.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CreatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential creation time",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"created_time": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Credential creation time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential description, length: 0 ~ 8192 characters",
		//	  "maxLength": 8192,
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential description, length: 0 ~ 8192 characters",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: EncryptionKey
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "KMS key TRN for encrypting credential value. If not specified, the default key of Credential Manager is used",
		//	  "type": "string"
		//	}
		"encryption_key": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "KMS key TRN for encrypting credential value. If not specified, the default key of Credential Manager is used",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ExtendedConfig
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential extension configuration, used to specify properties for non-Generic credentials",
		//	  "type": "string"
		//	}
		"extended_config": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential extension configuration, used to specify properties for non-Generic credentials",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: LastRotationTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential last rotation time",
		//	  "type": "string"
		//	}
		"last_rotation_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential last rotation time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Managed
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Is managed credential",
		//	  "type": "boolean"
		//	}
		"managed": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Is managed credential",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: OwningService
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Managed Cloud Service",
		//	  "type": "string"
		//	}
		"owning_service": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Managed Cloud Service",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: PendingWindowInDays
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential pre-deletion period. During this time, you can revoke the deletion of credentials in pending deletion status; after the pre-deletion period, deletion cannot be revoked. Value range: 7 ~ 30. Unit: days. Default: 7. To cancel, use CancelSecretDeletion.",
		//	  "type": "integer"
		//	}
		"pending_window_in_days": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Credential pre-deletion period. During this time, you can revoke the deletion of credentials in pending deletion status; after the pre-deletion period, deletion cannot be revoked. Value range: 7 ~ 30. Unit: days. Default: 7. To cancel, use CancelSecretDeletion.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential project name. Default value: default",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential project name. Default value: default",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: RotationInterval
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Automatic rotation interval. Range: 1 ~ 365 days. Format: integer[unit], where integer is the duration and unit is the time unit. Unit value: d (days). For example: 7d means a 7-day interval",
		//	  "type": "string"
		//	}
		"rotation_interval": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Automatic rotation interval. Range: 1 ~ 365 days. Format: integer[unit], where integer is the duration and unit is the time unit. Unit value: d (days). For example: 7d means a 7-day interval",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: RotationIntervalRead
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Automatic rotation interval, unit: seconds",
		//	  "type": "integer"
		//	}
		"rotation_interval_read": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Automatic rotation interval, unit: seconds",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: RotationState
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Rotation status: Enable: automatic rotation enabled, Disable: automatic rotation disabled, Rotating: automatic rotation in progress, None: automatic rotation not supported",
		//	  "type": "string"
		//	}
		"rotation_state": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Rotation status: Enable: automatic rotation enabled, Disable: automatic rotation disabled, Rotating: automatic rotation in progress, None: automatic rotation not supported",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ScheduleDeleteTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential Scheduled Deletion Time",
		//	  "type": "string"
		//	}
		"schedule_delete_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential Scheduled Deletion Time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ScheduleRotationTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential next rotation time",
		//	  "type": "string"
		//	}
		"schedule_rotation_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential next rotation time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SecretBackup
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Trigger: When set to true, calls the KMS BackupSecret API to back up the credential. The backup result is written to SecretRestoreRead. Please keep it safe.",
		//	  "type": "boolean"
		//	}
		"secret_backup": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Trigger: When set to true, calls the KMS BackupSecret API to back up the credential. The backup result is written to SecretRestoreRead. Please keep it safe.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SecretID
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential unique identifier, UUID format",
		//	  "type": "string"
		//	}
		"secret_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential unique identifier, UUID format",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SecretName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential name. Valid characters: [a-zA-Z0-9/_+=.@-]",
		//	  "type": "string"
		//	}
		"secret_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential name. Valid characters: [a-zA-Z0-9/_+=.@-]",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SecretRestore
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential restore parameters. Only effective during creation. If provided, calls the KMS RestoreSecret API to restore the credential from backup data. Other creation parameters such as SecretValue, SecretType, and SecretName will not take effect.",
		//	  "properties": {
		//	    "BackupData": {
		//	      "description": "Complete credential data returned by backup, in JSON format.",
		//	      "type": "string"
		//	    },
		//	    "SecretDataKey": {
		//	      "description": "Encrypted data key returned by backup, Base64 encoded.",
		//	      "type": "string"
		//	    },
		//	    "Signature": {
		//	      "description": "Signature of the backup data, Base64 encoded.",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "required": [
		//	    "BackupData",
		//	    "Signature",
		//	    "SecretDataKey"
		//	  ],
		//	  "type": "object"
		//	}
		"secret_restore": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: BackupData
				"backup_data": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Complete credential data returned by backup, in JSON format.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: SecretDataKey
				"secret_data_key": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Encrypted data key returned by backup, Base64 encoded.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Signature
				"signature": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Signature of the backup data, Base64 encoded.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Credential restore parameters. Only effective during creation. If provided, calls the KMS RestoreSecret API to restore the credential from backup data. Other creation parameters such as SecretValue, SecretType, and SecretName will not take effect.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SecretRestoreRead
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential restore parameters. Returned only during backup.",
		//	  "properties": {
		//	    "BackupData": {
		//	      "description": "Complete credential data returned by backup, in JSON format.",
		//	      "type": "string"
		//	    },
		//	    "SecretDataKey": {
		//	      "description": "Encrypted data key returned by backup, Base64 encoded.",
		//	      "type": "string"
		//	    },
		//	    "Signature": {
		//	      "description": "Signature of the backup data, Base64 encoded.",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "required": [
		//	    "BackupData",
		//	    "Signature",
		//	    "SecretDataKey"
		//	  ],
		//	  "type": "object"
		//	}
		"secret_restore_read": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: BackupData
				"backup_data": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Complete credential data returned by backup, in JSON format.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: SecretDataKey
				"secret_data_key": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Encrypted data key returned by backup, Base64 encoded.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Signature
				"signature": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Signature of the backup data, Base64 encoded.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Credential restore parameters. Returned only during backup.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SecretRotate
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Trigger: When set to true, calls the KMS RotateSecret API to manually rotate the credential.",
		//	  "type": "boolean"
		//	}
		"secret_rotate": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Trigger: When set to true, calls the KMS RotateSecret API to manually rotate the credential.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SecretState
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential status. Enable: enabled, Disable: disabled, PendingDelete: scheduled for deletion",
		//	  "type": "string"
		//	}
		"secret_state": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential status. Enable: enabled, Disable: disabled, PendingDelete: scheduled for deletion",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SecretType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential type. Currently supports Generic|IAM|RDS|Redis|ECS|PGSQL|SQLServer",
		//	  "type": "string"
		//	}
		"secret_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential type. Currently supports Generic|IAM|RDS|Redis|ECS|PGSQL|SQLServer",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SecretValue
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential value. When SecretType is Generic, users can customize it. It is recommended to use JSON key-value pairs",
		//	  "type": "string"
		//	}
		"secret_value": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential value. When SecretType is Generic, users can customize it. It is recommended to use JSON key-value pairs",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SecretVersions
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential version information.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "properties": {
		//	      "CreationDate": {
		//	        "description": "Credential version creation time.",
		//	        "format": "int64",
		//	        "type": "integer"
		//	      },
		//	      "VersionID": {
		//	        "description": "Unique identifier for the credential version, in UUID format.",
		//	        "type": "string"
		//	      },
		//	      "VersionStage": {
		//	        "description": "Credential version tags.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"secret_versions": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: CreationDate
					"creation_date": schema.Int64Attribute{ /*START ATTRIBUTE*/
						Description: "Credential version creation time.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: VersionID
					"version_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Unique identifier for the credential version, in UUID format.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: VersionStage
					"version_stage": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Credential version tags.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Credential version information.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Trn
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential resource name. Format: trn:kms:${Region}:${AccountID}:secrets/${secret}",
		//	  "type": "string"
		//	}
		"trn": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential resource name. Format: trn:kms:${Region}:${AccountID}:secrets/${secret}",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UID
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential tenant ID",
		//	  "type": "string"
		//	}
		"uid": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential tenant ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential update date",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"updated_time": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Credential update date",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: VersionName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Version alias. Valid characters: [a-zA-Z0-9/_+=.@-]",
		//	  "type": "string"
		//	}
		"version_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Version alias. Valid characters: [a-zA-Z0-9/_+=.@-]",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::KMS::Secret",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::KMS::Secret").WithTerraformTypeName("volcenginecc_kms_secret")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"automatic_rotation":     "AutomaticRotation",
		"backup_data":            "BackupData",
		"cancel_secret_deletion": "CancelSecretDeletion",
		"created_time":           "CreatedTime",
		"creation_date":          "CreationDate",
		"description":            "Description",
		"encryption_key":         "EncryptionKey",
		"extended_config":        "ExtendedConfig",
		"last_rotation_time":     "LastRotationTime",
		"managed":                "Managed",
		"owning_service":         "OwningService",
		"pending_window_in_days": "PendingWindowInDays",
		"project_name":           "ProjectName",
		"rotation_interval":      "RotationInterval",
		"rotation_interval_read": "RotationIntervalRead",
		"rotation_state":         "RotationState",
		"schedule_delete_time":   "ScheduleDeleteTime",
		"schedule_rotation_time": "ScheduleRotationTime",
		"secret_backup":          "SecretBackup",
		"secret_data_key":        "SecretDataKey",
		"secret_id":              "SecretID",
		"secret_name":            "SecretName",
		"secret_restore":         "SecretRestore",
		"secret_restore_read":    "SecretRestoreRead",
		"secret_rotate":          "SecretRotate",
		"secret_state":           "SecretState",
		"secret_type":            "SecretType",
		"secret_value":           "SecretValue",
		"secret_versions":        "SecretVersions",
		"signature":              "Signature",
		"trn":                    "Trn",
		"uid":                    "UID",
		"updated_time":           "UpdatedTime",
		"version_id":             "VersionID",
		"version_name":           "VersionName",
		"version_stage":          "VersionStage",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
