// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package tos

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
	fwvalidators "github.com/volcengine/terraform-provider-volcenginecc/internal/validators"
)

func init() {
	registry.AddResourceFactory("volcenginecc_tos_bucket_replication", bucketReplicationResource)
}

// bucketReplicationResource returns the Terraform volcenginecc_tos_bucket_replication resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::TOS::BucketReplication resource.
func bucketReplicationResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: Bucket
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the bucket to configure for cross-region replication",
		//	  "maxLength": 63,
		//	  "minLength": 3,
		//	  "type": "string"
		//	}
		"bucket": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the bucket to configure for cross-region replication",
			Required:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthBetween(3, 63),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Role
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Role name. The role must have read and write permissions for TOS and service access permissions. You can also use the default TOS role",
		//	  "type": "string"
		//	}
		"role": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Role name. The role must have read and write permissions for TOS and service access permissions. You can also use the default TOS role",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: Rules
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Replication rule information",
		//	  "insertionOrder": true,
		//	  "items": {
		//	    "description": "Single replication rule",
		//	    "properties": {
		//	      "AccessControlTranslation": {
		//	        "description": "Object owner management permissions",
		//	        "properties": {
		//	          "Owner": {
		//	            "description": "Object owner management permissions have been granted for replication to the destination bucket, allowing the destination bucket to read objects and grant other accounts permission to read objects",
		//	            "type": "string"
		//	          }
		//	        },
		//	        "required": [
		//	          "Owner"
		//	        ],
		//	        "type": "object"
		//	      },
		//	      "Destination": {
		//	        "description": "Replication target bucket information",
		//	        "properties": {
		//	          "Bucket": {
		//	            "description": "Name of the bucket storing object replicas identified by the rule",
		//	            "type": "string"
		//	          },
		//	          "Location": {
		//	            "description": "Region of the target bucket",
		//	            "type": "string"
		//	          },
		//	          "StorageClass": {
		//	            "description": "Specify the storage class for objects replicated to the target bucket. Options: STANDARD: Standard storage. STANDARD_IA: Infrequent access storage. GLACIER_IR: Archive instant retrieval storage. INTELLIGENT_TIERING: Intelligent tiering storage. ARCHIVE: Archive storage. COLD_ARCHIVE: Cold archive storage. DEEP_COLD_ARCHIVE: Deep cold archive storage",
		//	            "type": "string"
		//	          },
		//	          "StorageClassInheritDirective": {
		//	            "description": "Set the storage class for objects replicated to the target bucket. Options: SOURCE_OBJECT: Inherit the storage class of the source bucket object. DESTINATION_BUCKET: Inherit the default storage class of the target bucket",
		//	            "type": "string"
		//	          }
		//	        },
		//	        "required": [
		//	          "Bucket",
		//	          "Location"
		//	        ],
		//	        "type": "object"
		//	      },
		//	      "HistoricalObjectReplication": {
		//	        "description": "Enable historical object replication. If enabled, historical objects matching this rule will be replicated. Options: Enabled: Enable historical object replication. Disabled: Do not enable historical object replication",
		//	        "type": "string"
		//	      },
		//	      "ID": {
		//	        "description": "Unique identifier for the rule, less than 255 characters",
		//	        "type": "string"
		//	      },
		//	      "PrefixSet": {
		//	        "description": "Object name prefix to which this rule applies",
		//	        "items": {
		//	          "type": "string"
		//	        },
		//	        "type": "array"
		//	      },
		//	      "Progress": {
		//	        "description": "Save replication progress",
		//	        "properties": {
		//	          "HistoricalObject": {
		//	            "description": "Show the percentage of historical data that has been replicated",
		//	            "type": "number"
		//	          },
		//	          "NewObject": {
		//	            "description": "Show the timestamp when data is replicated to the target bucket",
		//	            "type": "string"
		//	          }
		//	        },
		//	        "type": "object"
		//	      },
		//	      "Status": {
		//	        "description": "Specify whether to enable this rule. Options: Enabled: Enable this rule. Disabled: Do not enable this rule",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "ID",
		//	      "Status",
		//	      "Destination",
		//	      "HistoricalObjectReplication"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"rules": schema.ListNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: AccessControlTranslation
					"access_control_translation": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
						Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
							// Property: Owner
							"owner": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Object owner management permissions have been granted for replication to the destination bucket, allowing the destination bucket to read objects and grant other accounts permission to read objects",
								Optional:    true,
								Computed:    true,
								Validators: []validator.String{ /*START VALIDATORS*/
									fwvalidators.NotNullString(),
								}, /*END VALIDATORS*/
								PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
									stringplanmodifier.UseStateForUnknown(),
								}, /*END PLAN MODIFIERS*/
							}, /*END ATTRIBUTE*/
						}, /*END SCHEMA*/
						Description: "Object owner management permissions",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
							objectplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Destination
					"destination": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
						Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
							// Property: Bucket
							"bucket": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Name of the bucket storing object replicas identified by the rule",
								Required:    true,
							}, /*END ATTRIBUTE*/
							// Property: Location
							"location": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Region of the target bucket",
								Required:    true,
							}, /*END ATTRIBUTE*/
							// Property: StorageClass
							"storage_class": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Specify the storage class for objects replicated to the target bucket. Options: STANDARD: Standard storage. STANDARD_IA: Infrequent access storage. GLACIER_IR: Archive instant retrieval storage. INTELLIGENT_TIERING: Intelligent tiering storage. ARCHIVE: Archive storage. COLD_ARCHIVE: Cold archive storage. DEEP_COLD_ARCHIVE: Deep cold archive storage",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
									stringplanmodifier.UseStateForUnknown(),
								}, /*END PLAN MODIFIERS*/
							}, /*END ATTRIBUTE*/
							// Property: StorageClassInheritDirective
							"storage_class_inherit_directive": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Set the storage class for objects replicated to the target bucket. Options: SOURCE_OBJECT: Inherit the storage class of the source bucket object. DESTINATION_BUCKET: Inherit the default storage class of the target bucket",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
									stringplanmodifier.UseStateForUnknown(),
								}, /*END PLAN MODIFIERS*/
							}, /*END ATTRIBUTE*/
						}, /*END SCHEMA*/
						Description: "Replication target bucket information",
						Required:    true,
					}, /*END ATTRIBUTE*/
					// Property: HistoricalObjectReplication
					"historical_object_replication": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Enable historical object replication. If enabled, historical objects matching this rule will be replicated. Options: Enabled: Enable historical object replication. Disabled: Do not enable historical object replication",
						Required:    true,
					}, /*END ATTRIBUTE*/
					// Property: ID
					"id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Unique identifier for the rule, less than 255 characters",
						Required:    true,
					}, /*END ATTRIBUTE*/
					// Property: PrefixSet
					"prefix_set": schema.ListAttribute{ /*START ATTRIBUTE*/
						ElementType: types.StringType,
						Description: "Object name prefix to which this rule applies",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{ /*START PLAN MODIFIERS*/
							listplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Progress
					"progress": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
						Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
							// Property: HistoricalObject
							"historical_object": schema.Float64Attribute{ /*START ATTRIBUTE*/
								Description: "Show the percentage of historical data that has been replicated",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: NewObject
							"new_object": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Show the timestamp when data is replicated to the target bucket",
								Computed:    true,
							}, /*END ATTRIBUTE*/
						}, /*END SCHEMA*/
						Description: "Save replication progress",
						Computed:    true,
						PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
							objectplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Status
					"status": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Specify whether to enable this rule. Options: Enabled: Enable this rule. Disabled: Do not enable this rule",
						Required:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Replication rule information\n Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.",
			Required:    true,
			Validators: []validator.List{ /*START VALIDATORS*/
				listvalidator.UniqueValues(),
			}, /*END VALIDATORS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Manage cross-region replication configuration for the specified TOS bucket. This resource uses the bucket as the primary key. Create and Update will write the replication role and rule set as a whole. Delete will remove the replication configuration from the bucket",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::TOS::BucketReplication").WithTerraformTypeName("volcenginecc_tos_bucket_replication")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"access_control_translation":      "AccessControlTranslation",
		"bucket":                          "Bucket",
		"destination":                     "Destination",
		"historical_object":               "HistoricalObject",
		"historical_object_replication":   "HistoricalObjectReplication",
		"id":                              "ID",
		"location":                        "Location",
		"new_object":                      "NewObject",
		"owner":                           "Owner",
		"prefix_set":                      "PrefixSet",
		"progress":                        "Progress",
		"role":                            "Role",
		"rules":                           "Rules",
		"status":                          "Status",
		"storage_class":                   "StorageClass",
		"storage_class_inherit_directive": "StorageClassInheritDirective",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/Rules/*/Progress",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/Bucket",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
