// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package tls

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_tls_download_task", downloadTaskResource)
}

// downloadTaskResource returns the Terraform volcenginecc_tls_download_task resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::TLS::DownloadTask resource.
func downloadTaskResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AllowIncomplete
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Whether to allow approximate results when the query statement cannot be calculated precisely.",
		//	  "type": "boolean"
		//	}
		"allow_incomplete": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Whether to allow approximate results when the query statement cannot be calculated precisely.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
				boolplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Compression
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Compression format of the exported file. none: no compression. Recommended only for small data volumes. gzip: compress using gzip format. ip: compress using ip format.",
		//	  "type": "string"
		//	}
		"compression": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Compression format of the exported file. none: no compression. Recommended only for small data volumes. gzip: compress using gzip format. ip: compress using ip format.",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: CreateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Download task creation time.",
		//	  "type": "string"
		//	}
		"create_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Download task creation time.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: DataFormat
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Exported file format. Supported values: csv: CSV format. json: JSON format. jsonl: JSONL format.",
		//	  "type": "string"
		//	}
		"data_format": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Exported file format. Supported values: csv: CSV format. json: JSON format. jsonl: JSONL format.",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: EndTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Query end time, accurate to the millisecond. Unix timestamp format, representing the number of milliseconds since 1970-1-1 00:00:00 UTC.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"end_time": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Query end time, accurate to the millisecond. Unix timestamp format, representing the number of milliseconds since 1970-1-1 00:00:00 UTC.",
			Required:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
			// EndTime is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: EndTimeStr
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Query end time.",
		//	  "type": "string"
		//	}
		"end_time_str": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Query end time.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Limit
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Number of original log entries downloaded, or number of rows in the analysis result.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"limit": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Number of original log entries downloaded, or number of rows in the analysis result.",
			Required:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
			// Limit is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: LogContextInfos
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Download the log information required for context queries, including the source host, LogGroup ID, and the log's sequence number within the LogGroup. Set this parameter when TaskType is 2.",
		//	  "properties": {
		//	    "ContextFlow": {
		//	      "description": "LogGroup ID to which the log context belongs.",
		//	      "type": "string"
		//	    },
		//	    "PackageOffset": {
		//	      "description": "Specifies the log index in the LogGroup.",
		//	      "format": "int64",
		//	      "type": "integer"
		//	    },
		//	    "Source": {
		//	      "description": "Host of the log source.",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"log_context_infos": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: ContextFlow
				"context_flow": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "LogGroup ID to which the log context belongs.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: PackageOffset
				"package_offset": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Specifies the log index in the LogGroup.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: Source
				"source": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Host of the log source.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Download the log information required for context queries, including the source host, LogGroup ID, and the log's sequence number within the LogGroup. Set this parameter when TaskType is 2.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
				objectplanmodifier.UseStateForUnknown(),
				objectplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: LogCount
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Number of log entries included in the download task.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"log_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Number of log entries included in the download task.",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: LogSize
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Total size of logs included in the download task, in bytes.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"log_size": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Total size of logs included in the download task, in bytes.",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: MustComplete
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Whether to use fully accurate query results for download. true: use fully accurate query results to ensure the downloaded log data exactly matches the query conditions. false: full accuracy is not required; allows downloading log data that may not exactly match the query conditions.",
		//	  "type": "boolean"
		//	}
		"must_complete": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Whether to use fully accurate query results for download. true: use fully accurate query results to ensure the downloaded log data exactly matches the query conditions. false: full accuracy is not required; allows downloading log data that may not exactly match the query conditions.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
				boolplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
			// MustComplete is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: Query
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Query statement for analysis, with a maximum length of 4 KiB.",
		//	  "type": "string"
		//	}
		"query": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Query statement for analysis, with a maximum length of 4 KiB.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Sort
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Log sorting order when only retrieving without analysis. asc: ascending. desc: descending.",
		//	  "type": "string"
		//	}
		"sort": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Log sorting order when only retrieving without analysis. asc: ascending. desc: descending.",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
			// Sort is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: StartTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Query start time, accurate to the millisecond. Unix timestamp format, representing the number of milliseconds since 1970-1-1 00:00:00 UTC.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"start_time": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Query start time, accurate to the millisecond. Unix timestamp format, representing the number of milliseconds since 1970-1-1 00:00:00 UTC.",
			Required:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
			// StartTime is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: StartTimeStr
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Query start time.",
		//	  "type": "string"
		//	}
		"start_time_str": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Query start time.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TaskId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Download task ID.",
		//	  "type": "string"
		//	}
		"task_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Download task ID.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TaskName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Download task name. Length range: 1–63 characters.",
		//	  "type": "string"
		//	}
		"task_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Download task name. Length range: 1–63 characters.",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TaskStatus
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Download task status, indicating the generation status of the log archive file. Includes: creating: file is being generated. created_cut: file has been partially generated. success: file has been generated. wait: waiting. fail: failed.",
		//	  "type": "string"
		//	}
		"task_status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Download task status, indicating the generation status of the log archive file. Includes: creating: file is being generated. created_cut: file has been partially generated. success: file has been generated. wait: waiting. fail: failed.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TaskType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Type of logs to download. 0: download search-type logs. 1: download analysis-type logs. 2: download context-type logs.",
		//	  "type": "integer"
		//	}
		"task_type": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Type of logs to download. 0: download search-type logs. 1: download analysis-type logs. 2: download context-type logs.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
				int64planmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TopicId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Log topic ID to which the download task belongs.",
		//	  "type": "string"
		//	}
		"topic_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Log topic ID to which the download task belongs.",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Log download task, used to export log data retrieved from a log topic as a file for user download.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::TLS::DownloadTask").WithTerraformTypeName("volcenginecc_tls_download_task")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"allow_incomplete":  "AllowIncomplete",
		"compression":       "Compression",
		"context_flow":      "ContextFlow",
		"create_time":       "CreateTime",
		"data_format":       "DataFormat",
		"end_time":          "EndTime",
		"end_time_str":      "EndTimeStr",
		"limit":             "Limit",
		"log_context_infos": "LogContextInfos",
		"log_count":         "LogCount",
		"log_size":          "LogSize",
		"must_complete":     "MustComplete",
		"package_offset":    "PackageOffset",
		"query":             "Query",
		"sort":              "Sort",
		"source":            "Source",
		"start_time":        "StartTime",
		"start_time_str":    "StartTimeStr",
		"task_id":           "TaskId",
		"task_name":         "TaskName",
		"task_status":       "TaskStatus",
		"task_type":         "TaskType",
		"topic_id":          "TopicId",
	})

	opts = opts.WithWriteOnlyPropertyPaths([]string{
		"/properties/StartTime",
		"/properties/EndTime",
		"/properties/MustComplete",
		"/properties/Limit",
		"/properties/Sort",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/TaskId",
		"/properties/LogCount",
		"/properties/LogSize",
		"/properties/TaskStatus",
		"/properties/CreateTime",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/TopicId",
		"/properties/TaskName",
		"/properties/Query",
		"/properties/StartTime",
		"/properties/EndTime",
		"/properties/Compression",
		"/properties/DataFormat",
		"/properties/Limit",
		"/properties/Sort",
		"/properties/TaskType",
		"/properties/AllowIncomplete",
		"/properties/LogContextInfos",
		"/properties/MustComplete",
		"/properties/StartTimeStr",
		"/properties/EndTimeStr",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
