// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package tls

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_tls_rule_bound_host_group", ruleBoundHostGroupResource)
}

// ruleBoundHostGroupResource returns the Terraform volcenginecc_tls_rule_bound_host_group resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::TLS::RuleBoundHostGroup resource.
func ruleBoundHostGroupResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: HostGroup
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Bound machine group configuration information",
		//	  "properties": {
		//	    "AbnormalHeartbeatStatusCount": {
		//	      "description": "Number of machines with abnormal heartbeat status",
		//	      "format": "int64",
		//	      "type": "integer"
		//	    },
		//	    "AgentLatestVersion": {
		//	      "description": "Latest LogCollector version number available for upgrade",
		//	      "type": "string"
		//	    },
		//	    "AutoUpdate": {
		//	      "description": "Enable LogCollector auto upgrade on machine group servers. true: The log service will check upgrade conditions during the specified time period each day. If conditions are met, LogCollector will be upgraded automatically without manual intervention. false (default): LogCollector will not upgrade automatically. To use a newer version, refer to the LogCollector upgrade procedure.",
		//	      "type": "boolean"
		//	    },
		//	    "CreateTime": {
		//	      "description": "Machine group creation time",
		//	      "type": "string"
		//	    },
		//	    "HostCount": {
		//	      "description": "Number of machines in the machine group",
		//	      "format": "int64",
		//	      "type": "integer"
		//	    },
		//	    "HostGroupId": {
		//	      "description": "Machine group ID",
		//	      "type": "string"
		//	    },
		//	    "HostGroupName": {
		//	      "description": "Machine group name",
		//	      "type": "string"
		//	    },
		//	    "HostGroupType": {
		//	      "description": "Machine group type. IP: machine IP. Label: machine label.",
		//	      "type": "string"
		//	    },
		//	    "HostIdentifier": {
		//	      "description": "Machine identifier",
		//	      "type": "string"
		//	    },
		//	    "IamProjectName": {
		//	      "description": "IAM project associated with the machine group",
		//	      "type": "string"
		//	    },
		//	    "ModifyTime": {
		//	      "description": "Machine group modification time",
		//	      "type": "string"
		//	    },
		//	    "NormalHeartbeatStatusCount": {
		//	      "description": "Number of machines with normal heartbeat status",
		//	      "format": "int64",
		//	      "type": "integer"
		//	    },
		//	    "RuleCount": {
		//	      "description": "Number of collection configurations bound to the machine group",
		//	      "format": "int64",
		//	      "type": "integer"
		//	    },
		//	    "ServiceLogging": {
		//	      "description": "Enable LogCollector service log feature. true: enabled. false (default): disabled.",
		//	      "type": "boolean"
		//	    },
		//	    "UpdateEndTime": {
		//	      "description": "LogCollector auto upgrade end time",
		//	      "type": "string"
		//	    },
		//	    "UpdateStartTime": {
		//	      "description": "LogCollector auto upgrade start time. Note: Only required when AutoUpdate is set to true. It is recommended to schedule auto upgrade during off-peak hours. LogCollector may restart during the upgrade process, but logs will not be lost.",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"host_group": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: AbnormalHeartbeatStatusCount
				"abnormal_heartbeat_status_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Number of machines with abnormal heartbeat status",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: AgentLatestVersion
				"agent_latest_version": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Latest LogCollector version number available for upgrade",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: AutoUpdate
				"auto_update": schema.BoolAttribute{ /*START ATTRIBUTE*/
					Description: "Enable LogCollector auto upgrade on machine group servers. true: The log service will check upgrade conditions during the specified time period each day. If conditions are met, LogCollector will be upgraded automatically without manual intervention. false (default): LogCollector will not upgrade automatically. To use a newer version, refer to the LogCollector upgrade procedure.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: CreateTime
				"create_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Machine group creation time",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: HostCount
				"host_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Number of machines in the machine group",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: HostGroupId
				"host_group_id": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Machine group ID",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: HostGroupName
				"host_group_name": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Machine group name",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: HostGroupType
				"host_group_type": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Machine group type. IP: machine IP. Label: machine label.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: HostIdentifier
				"host_identifier": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Machine identifier",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: IamProjectName
				"iam_project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "IAM project associated with the machine group",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ModifyTime
				"modify_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Machine group modification time",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: NormalHeartbeatStatusCount
				"normal_heartbeat_status_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Number of machines with normal heartbeat status",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: RuleCount
				"rule_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Number of collection configurations bound to the machine group",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ServiceLogging
				"service_logging": schema.BoolAttribute{ /*START ATTRIBUTE*/
					Description: "Enable LogCollector service log feature. true: enabled. false (default): disabled.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: UpdateEndTime
				"update_end_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "LogCollector auto upgrade end time",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: UpdateStartTime
				"update_start_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "LogCollector auto upgrade start time. Note: Only required when AutoUpdate is set to true. It is recommended to schedule auto upgrade during off-peak hours. LogCollector may restart during the upgrade process, but logs will not be lost.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Bound machine group configuration information",
			Computed:    true,
			PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
				objectplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: HostGroupId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Machine group ID",
		//	  "type": "string"
		//	}
		"host_group_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Machine group ID",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: RuleId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Collection configuration ID",
		//	  "type": "string"
		//	}
		"rule_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Collection configuration ID",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Resource representing the binding relationship between collection configuration and machine group",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::TLS::RuleBoundHostGroup").WithTerraformTypeName("volcenginecc_tls_rule_bound_host_group")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"abnormal_heartbeat_status_count": "AbnormalHeartbeatStatusCount",
		"agent_latest_version":            "AgentLatestVersion",
		"auto_update":                     "AutoUpdate",
		"create_time":                     "CreateTime",
		"host_count":                      "HostCount",
		"host_group":                      "HostGroup",
		"host_group_id":                   "HostGroupId",
		"host_group_name":                 "HostGroupName",
		"host_group_type":                 "HostGroupType",
		"host_identifier":                 "HostIdentifier",
		"iam_project_name":                "IamProjectName",
		"modify_time":                     "ModifyTime",
		"normal_heartbeat_status_count":   "NormalHeartbeatStatusCount",
		"rule_count":                      "RuleCount",
		"rule_id":                         "RuleId",
		"service_logging":                 "ServiceLogging",
		"update_end_time":                 "UpdateEndTime",
		"update_start_time":               "UpdateStartTime",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/HostGroup",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/RuleId",
		"/properties/HostGroupId",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
