// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package cloudmonitor

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_cloudmonitor_contact", contactResource)
}

// contactResource returns the Terraform volcenginecc_cloudmonitor_contact resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::CloudMonitor::Contact resource.
func contactResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: ContactGroupIds
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "List of contact group IDs the contact has joined. A single contact can be added to up to 10 contact groups. The value will replace the contact's existing associated groups.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "maxItems": 10,
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"contact_group_ids": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "List of contact group IDs the contact has joined. A single contact can be added to up to 10 contact groups. The value will replace the contact's existing associated groups.",
			Optional:    true,
			Computed:    true,
			Validators: []validator.Set{ /*START VALIDATORS*/
				setvalidator.SizeAtMost(10),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ContactId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Alert contact ID.",
		//	  "type": "string"
		//	}
		"contact_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Alert contact ID.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Email
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Required when updating. Alert email address. Cloud Monitoring will send a verification email to the provided address. You must open the verification link in the email to complete verification. Only after the email address is verified can it receive alert notifications.",
		//	  "type": "string"
		//	}
		"email": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Required when updating. Alert email address. Cloud Monitoring will send a verification email to the provided address. You must open the verification link in the email to complete verification. Only after the email address is verified can it receive alert notifications.",
			Required:    true,
			// Email is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: Name
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Contact name. Cannot start with a digit or hyphen. Can only contain Chinese characters, letters, digits, underscores (_), and hyphens (-). Length must be between 1 and 128 characters.",
		//	  "maxLength": 128,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Contact name. Cannot start with a digit or hyphen. Can only contain Chinese characters, letters, digits, underscores (_), and hyphens (-). Length must be between 1 and 128 characters.",
			Required:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthBetween(1, 128),
			}, /*END VALIDATORS*/
		}, /*END ATTRIBUTE*/
		// Property: Phone
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Alert phone number. If not provided during update, the original value remains. Cloud Monitoring will send a verification SMS to the provided phone number. You must open the verification link in the SMS to complete verification. Only after the phone number is verified can it receive alert messages.",
		//	  "type": "string"
		//	}
		"phone": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Alert phone number. If not provided during update, the original value remains. Cloud Monitoring will send a verification SMS to the provided phone number. You must open the verification link in the SMS to complete verification. Only after the phone number is verified can it receive alert messages.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
			// Phone is a write-only property.
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Cloud Monitoring alert contact. Used to configure recipients for alert notifications. You can add a contact to one or more contact groups.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::CloudMonitor::Contact").WithTerraformTypeName("volcenginecc_cloudmonitor_contact")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"contact_group_ids": "ContactGroupIds",
		"contact_id":        "ContactId",
		"email":             "Email",
		"name":              "Name",
		"phone":             "Phone",
	})

	opts = opts.WithWriteOnlyPropertyPaths([]string{
		"/properties/Email",
		"/properties/Phone",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/ContactId",
	})

	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
