// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package cloudmonitor

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_cloudmonitor_contact", contactDataSource)
}

// contactDataSource returns the Terraform volcenginecc_cloudmonitor_contact data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::CloudMonitor::Contact resource.
func contactDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: ContactGroupIds
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "List of contact group IDs the contact has joined. A single contact can be added to up to 10 contact groups. The value will replace the contact's existing associated groups.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "maxItems": 10,
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"contact_group_ids": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "List of contact group IDs the contact has joined. A single contact can be added to up to 10 contact groups. The value will replace the contact's existing associated groups.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ContactId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Alert contact ID.",
		//	  "type": "string"
		//	}
		"contact_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Alert contact ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Email
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Required when updating. Alert email address. Cloud Monitoring will send a verification email to the provided address. You must open the verification link in the email to complete verification. Only after the email address is verified can it receive alert notifications.",
		//	  "type": "string"
		//	}
		"email": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Required when updating. Alert email address. Cloud Monitoring will send a verification email to the provided address. You must open the verification link in the email to complete verification. Only after the email address is verified can it receive alert notifications.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Name
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Contact name. Cannot start with a digit or hyphen. Can only contain Chinese characters, letters, digits, underscores (_), and hyphens (-). Length must be between 1 and 128 characters.",
		//	  "maxLength": 128,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Contact name. Cannot start with a digit or hyphen. Can only contain Chinese characters, letters, digits, underscores (_), and hyphens (-). Length must be between 1 and 128 characters.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Phone
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Alert phone number. If not provided during update, the original value remains. Cloud Monitoring will send a verification SMS to the provided phone number. You must open the verification link in the SMS to complete verification. Only after the phone number is verified can it receive alert messages.",
		//	  "type": "string"
		//	}
		"phone": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Alert phone number. If not provided during update, the original value remains. Cloud Monitoring will send a verification SMS to the provided phone number. You must open the verification link in the SMS to complete verification. Only after the phone number is verified can it receive alert messages.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::CloudMonitor::Contact",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::CloudMonitor::Contact").WithTerraformTypeName("volcenginecc_cloudmonitor_contact")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"contact_group_ids": "ContactGroupIds",
		"contact_id":        "ContactId",
		"email":             "Email",
		"name":              "Name",
		"phone":             "Phone",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
