// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package certificateservice

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_certificateservice_organization_info", organizationInfoDataSource)
}

// organizationInfoDataSource returns the Terraform volcenginecc_certificateservice_organization_info data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::CertificateService::OrganizationInfo resource.
func organizationInfoDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: Account
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Account ID associated with the information template.",
		//	  "type": "string"
		//	}
		"account": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Account ID associated with the information template.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Address
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enterprise address. Required when Type is Enterprise.",
		//	  "type": "string"
		//	}
		"address": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Enterprise address. Required when Type is Enterprise.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: BusinessLicenseNo
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enterprise unified social credit code.",
		//	  "type": "string"
		//	}
		"business_license_no": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Enterprise unified social credit code.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: City
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "City where the enterprise is located. Required when Type is Enterprise.",
		//	  "type": "string"
		//	}
		"city": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "City where the enterprise is located. Required when Type is Enterprise.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Contact
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Contact information for the information template.",
		//	  "properties": {
		//	    "Email": {
		//	      "description": "Contact person's email address.",
		//	      "type": "string"
		//	    },
		//	    "FirstName": {
		//	      "description": "Contact person's given name.",
		//	      "type": "string"
		//	    },
		//	    "IdCardNo": {
		//	      "description": "Contact person's ID number.",
		//	      "type": "string"
		//	    },
		//	    "LastName": {
		//	      "description": "Contact person's surname.",
		//	      "type": "string"
		//	    },
		//	    "Phone": {
		//	      "description": "Contact person's phone number.",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"contact": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Email
				"email": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Contact person's email address.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: FirstName
				"first_name": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Contact person's given name.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: IdCardNo
				"id_card_no": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Contact person's ID number.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: LastName
				"last_name": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Contact person's surname.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Phone
				"phone": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Contact person's phone number.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Contact information for the information template.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Country
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Two-letter country code where the enterprise is located, e.g., CN. Required when Type is Enterprise.",
		//	  "type": "string"
		//	}
		"country": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Two-letter country code where the enterprise is located, e.g., CN. Required when Type is Enterprise.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CreatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation time of the information template.",
		//	  "type": "string"
		//	}
		"created_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation time of the information template.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Department
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enterprise department.",
		//	  "type": "string"
		//	}
		"department": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Enterprise department.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Email
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enterprise email address.",
		//	  "type": "string"
		//	}
		"email": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Enterprise email address.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Name
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enterprise name. Required when Type is Enterprise.",
		//	  "type": "string"
		//	}
		"name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Enterprise name. Required when Type is Enterprise.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: OrganizationId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Information template ID, prefixed with org-, for example org-879f6502723b4e0f8762cf3528f4****.",
		//	  "type": "string"
		//	}
		"organization_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Information template ID, prefixed with org-, for example org-879f6502723b4e0f8762cf3528f4****.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: PostalCode
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Postal code, only for mainland China.",
		//	  "type": "string"
		//	}
		"postal_code": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Postal code, only for mainland China.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Project name associated with the information template. Default is default.",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Project name associated with the information template. Default is default.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Province
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Province where the enterprise is located. Required when Type is Enterprise.",
		//	  "type": "string"
		//	}
		"province": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Province where the enterprise is located. Required when Type is Enterprise.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Tag
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the information template.",
		//	  "type": "string"
		//	}
		"tag": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the information template.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "List of resource tags bound to the information template.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Resource tag.",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Tag key.",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Tag value.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key",
		//	      "Value"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag key.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag value.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "List of resource tags bound to the information template.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Type
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Information template type. Individual: Personal, can only apply for DV certificates. Enterprise: Enterprise, can apply for DV/OV/EV certificates.",
		//	  "type": "string"
		//	}
		"type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Information template type. Individual: Personal, can only apply for DV certificates. Enterprise: Enterprise, can apply for DV/OV/EV certificates.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::CertificateService::OrganizationInfo",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::CertificateService::OrganizationInfo").WithTerraformTypeName("volcenginecc_certificateservice_organization_info")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"account":             "Account",
		"address":             "Address",
		"business_license_no": "BusinessLicenseNo",
		"city":                "City",
		"contact":             "Contact",
		"country":             "Country",
		"created_time":        "CreatedTime",
		"department":          "Department",
		"email":               "Email",
		"first_name":          "FirstName",
		"id_card_no":          "IdCardNo",
		"key":                 "Key",
		"last_name":           "LastName",
		"name":                "Name",
		"organization_id":     "OrganizationId",
		"phone":               "Phone",
		"postal_code":         "PostalCode",
		"project_name":        "ProjectName",
		"province":            "Province",
		"tag":                 "Tag",
		"tags":                "Tags",
		"type":                "Type",
		"value":               "Value",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
