// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package certificateservice

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
	fwvalidators "github.com/volcengine/terraform-provider-volcenginecc/internal/validators"
)

func init() {
	registry.AddResourceFactory("volcenginecc_certificateservice_organization_info", organizationInfoResource)
}

// organizationInfoResource returns the Terraform volcenginecc_certificateservice_organization_info resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::CertificateService::OrganizationInfo resource.
func organizationInfoResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: Account
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Account ID associated with the information template.",
		//	  "type": "string"
		//	}
		"account": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Account ID associated with the information template.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Address
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enterprise address. Required when Type is Enterprise.",
		//	  "type": "string"
		//	}
		"address": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Enterprise address. Required when Type is Enterprise.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: BusinessLicenseNo
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enterprise unified social credit code.",
		//	  "type": "string"
		//	}
		"business_license_no": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Enterprise unified social credit code.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: City
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "City where the enterprise is located. Required when Type is Enterprise.",
		//	  "type": "string"
		//	}
		"city": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "City where the enterprise is located. Required when Type is Enterprise.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Contact
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Contact information for the information template.",
		//	  "properties": {
		//	    "Email": {
		//	      "description": "Contact person's email address.",
		//	      "type": "string"
		//	    },
		//	    "FirstName": {
		//	      "description": "Contact person's given name.",
		//	      "type": "string"
		//	    },
		//	    "IdCardNo": {
		//	      "description": "Contact person's ID number.",
		//	      "type": "string"
		//	    },
		//	    "LastName": {
		//	      "description": "Contact person's surname.",
		//	      "type": "string"
		//	    },
		//	    "Phone": {
		//	      "description": "Contact person's phone number.",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"contact": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Email
				"email": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Contact person's email address.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseNonNullStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: FirstName
				"first_name": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Contact person's given name.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseNonNullStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: IdCardNo
				"id_card_no": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Contact person's ID number.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseNonNullStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: LastName
				"last_name": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Contact person's surname.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseNonNullStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: Phone
				"phone": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Contact person's phone number.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseNonNullStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Contact information for the information template.",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: Country
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Two-letter country code where the enterprise is located, e.g., CN. Required when Type is Enterprise.",
		//	  "type": "string"
		//	}
		"country": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Two-letter country code where the enterprise is located, e.g., CN. Required when Type is Enterprise.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: CreatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation time of the information template.",
		//	  "type": "string"
		//	}
		"created_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation time of the information template.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Department
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enterprise department.",
		//	  "type": "string"
		//	}
		"department": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Enterprise department.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Email
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enterprise email address.",
		//	  "type": "string"
		//	}
		"email": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Enterprise email address.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Name
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enterprise name. Required when Type is Enterprise.",
		//	  "type": "string"
		//	}
		"name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Enterprise name. Required when Type is Enterprise.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: OrganizationId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Information template ID, prefixed with org-, for example org-879f6502723b4e0f8762cf3528f4****.",
		//	  "type": "string"
		//	}
		"organization_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Information template ID, prefixed with org-, for example org-879f6502723b4e0f8762cf3528f4****.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: PostalCode
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Postal code, only for mainland China.",
		//	  "type": "string"
		//	}
		"postal_code": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Postal code, only for mainland China.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Project name associated with the information template. Default is default.",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Project name associated with the information template. Default is default.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Province
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Province where the enterprise is located. Required when Type is Enterprise.",
		//	  "type": "string"
		//	}
		"province": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Province where the enterprise is located. Required when Type is Enterprise.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Tag
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the information template.",
		//	  "type": "string"
		//	}
		"tag": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the information template.",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "List of resource tags bound to the information template.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Resource tag.",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Tag key.",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Tag value.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key",
		//	      "Value"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag key.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{ /*START VALIDATORS*/
							fwvalidators.NotNullString(),
						}, /*END VALIDATORS*/
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseNonNullStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag value.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{ /*START VALIDATORS*/
							fwvalidators.NotNullString(),
						}, /*END VALIDATORS*/
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseNonNullStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "List of resource tags bound to the information template.\n Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Type
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Information template type. Individual: Personal, can only apply for DV certificates. Enterprise: Enterprise, can apply for DV/OV/EV certificates.",
		//	  "type": "string"
		//	}
		"type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Information template type. Individual: Personal, can only apply for DV certificates. Enterprise: Enterprise, can apply for DV/OV/EV certificates.",
			Required:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Organization Info template in Certificate Center. Used to reuse enterprise or individual identity information when applying for SSL certificates, including organization name, address, contact person, and other details.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::CertificateService::OrganizationInfo").WithTerraformTypeName("volcenginecc_certificateservice_organization_info")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"account":             "Account",
		"address":             "Address",
		"business_license_no": "BusinessLicenseNo",
		"city":                "City",
		"contact":             "Contact",
		"country":             "Country",
		"created_time":        "CreatedTime",
		"department":          "Department",
		"email":               "Email",
		"first_name":          "FirstName",
		"id_card_no":          "IdCardNo",
		"key":                 "Key",
		"last_name":           "LastName",
		"name":                "Name",
		"organization_id":     "OrganizationId",
		"phone":               "Phone",
		"postal_code":         "PostalCode",
		"project_name":        "ProjectName",
		"province":            "Province",
		"tag":                 "Tag",
		"tags":                "Tags",
		"type":                "Type",
		"value":               "Value",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/OrganizationId",
		"/properties/Account",
		"/properties/CreatedTime",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/ProjectName",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
