// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package transitrouter

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_transitrouter_transit_router_traffic_qos_queue_policy", transitRouterTrafficQosQueuePolicyDataSource)
}

// transitRouterTrafficQosQueuePolicyDataSource returns the Terraform volcenginecc_transitrouter_transit_router_traffic_qos_queue_policy data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::TransitRouter::TransitRouterTrafficQosQueuePolicy resource.
func transitRouterTrafficQosQueuePolicyDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CreationTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation time of the flow queue policy.",
		//	  "type": "string"
		//	}
		"creation_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation time of the flow queue policy.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Description of the flow queue policy. Must start with a letter, number, or Chinese character. Can contain letters, numbers, Chinese characters, and the following special characters: English comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。). Length must be from 0 to 255 characters.",
		//	  "maxLength": 255,
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Description of the flow queue policy. Must start with a letter, number, or Chinese character. Can contain letters, numbers, Chinese characters, and the following special characters: English comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。). Length must be from 0 to 255 characters.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status of the flow queue policy. Creating: being created. Deleting: being deleted. Pending: being configured. Available: available.",
		//	  "enum": [
		//	    "Creating",
		//	    "Deleting",
		//	    "Pending",
		//	    "Available"
		//	  ],
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Status of the flow queue policy. Creating: being created. Deleting: being deleted. Pending: being configured. Available: available.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Transit router instance ID.",
		//	  "type": "string"
		//	}
		"transit_router_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Transit router instance ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterTrafficQosQueuePolicyId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Flow queue policy ID.",
		//	  "type": "string"
		//	}
		"transit_router_traffic_qos_queue_policy_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Flow queue policy ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterTrafficQosQueuePolicyName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the flow queue policy. Must start with a letter, number, or Chinese character. Can contain letters, numbers, Chinese characters, and the following special characters: period (.), underscore (_), and hyphen (-). Length must be from 1 to 128 characters. If this parameter is not provided or no value is specified, the default is the flow queue policy ID.",
		//	  "maxLength": 128,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"transit_router_traffic_qos_queue_policy_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the flow queue policy. Must start with a letter, number, or Chinese character. Can contain letters, numbers, Chinese characters, and the following special characters: period (.), underscore (_), and hyphen (-). Length must be from 1 to 128 characters. If this parameter is not provided or no value is specified, the default is the flow queue policy ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Last update time of the flow queue policy.",
		//	  "type": "string"
		//	}
		"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Last update time of the flow queue policy.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::TransitRouter::TransitRouterTrafficQosQueuePolicy",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::TransitRouter::TransitRouterTrafficQosQueuePolicy").WithTerraformTypeName("volcenginecc_transitrouter_transit_router_traffic_qos_queue_policy")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"creation_time":     "CreationTime",
		"description":       "Description",
		"status":            "Status",
		"transit_router_id": "TransitRouterId",
		"transit_router_traffic_qos_queue_policy_id":   "TransitRouterTrafficQosQueuePolicyId",
		"transit_router_traffic_qos_queue_policy_name": "TransitRouterTrafficQosQueuePolicyName",
		"update_time": "UpdateTime",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
