// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package transitrouter

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_transitrouter_transit_router_attachment_to_route_table", transitRouterAttachmentToRouteTableDataSource)
}

// transitRouterAttachmentToRouteTableDataSource returns the Terraform volcenginecc_transitrouter_transit_router_attachment_to_route_table data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::TransitRouter::TransitRouterAttachmentToRouteTable resource.
func transitRouterAttachmentToRouteTableDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status of the associated forwarding. Possible values: Available (可用), Creating (创建中), Pending (配置中), Deleting (删除中).",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Status of the associated forwarding. Possible values: Available (可用), Creating (创建中), Pending (配置中), Deleting (删除中).",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterAttachmentId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the network instance connection. You can call APIs such as DescribeTransitRouterVpcAttachments, DescribeTransitRouterVpnAttachments, DescribeTransitRouterDirectConnectGatewayAttachments, and DescribeTransitRouterPeerAttachments to obtain the ID of the corresponding type of network instance connection.",
		//	  "type": "string"
		//	}
		"transit_router_attachment_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the network instance connection. You can call APIs such as DescribeTransitRouterVpcAttachments, DescribeTransitRouterVpnAttachments, DescribeTransitRouterDirectConnectGatewayAttachments, and DescribeTransitRouterPeerAttachments to obtain the ID of the corresponding type of network instance connection.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterRouteTableId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the route table associated with the Transit Router instance. You can call the DescribeTransitRouterRouteTables API to obtain the TR route table ID.",
		//	  "type": "string"
		//	}
		"transit_router_route_table_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the route table associated with the Transit Router instance. You can call the DescribeTransitRouterRouteTables API to obtain the TR route table ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::TransitRouter::TransitRouterAttachmentToRouteTable",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::TransitRouter::TransitRouterAttachmentToRouteTable").WithTerraformTypeName("volcenginecc_transitrouter_transit_router_attachment_to_route_table")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"status":                        "Status",
		"transit_router_attachment_id":  "TransitRouterAttachmentId",
		"transit_router_route_table_id": "TransitRouterRouteTableId",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
