// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package transitrouter

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_transitrouter_transit_router_forward_policy_table", transitRouterForwardPolicyTableDataSource)
}

// transitRouterForwardPolicyTableDataSource returns the Terraform volcenginecc_transitrouter_transit_router_forward_policy_table data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::TransitRouter::TransitRouterForwardPolicyTable resource.
func transitRouterForwardPolicyTableDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CreationTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation time of the forwarding policy.",
		//	  "type": "string"
		//	}
		"creation_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation time of the forwarding policy.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Description of the forwarding policy. Must start with a letter, number, or Chinese character. Can include letters, numbers, Chinese characters, and the following special characters: comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。). Length limit: 0–255 characters.",
		//	  "maxLength": 255,
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Description of the forwarding policy. Must start with a letter, number, or Chinese character. Can include letters, numbers, Chinese characters, and the following special characters: comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。). Length limit: 0–255 characters.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status of the forwarding policy. Creating: Being created. Deleting: Being deleted. Pending: Being configured. Available: Available.",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Status of the forwarding policy. Creating: Being created. Deleting: Being deleted. Pending: Being configured. Available: Available.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterAttachmentIds
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "List of associated IDs for the transit router instance.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"transit_router_attachment_ids": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "List of associated IDs for the transit router instance.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterForwardPolicyTableId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Forwarding policy ID.",
		//	  "type": "string"
		//	}
		"transit_router_forward_policy_table_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Forwarding policy ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterForwardPolicyTableName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the forwarding policy. Must start with a letter, number, or Chinese character. Can include letters, numbers, Chinese characters, and the following special characters: period (.), underscore (_), and hyphen (-). Length limit: 1–128 characters. If this parameter is not provided or no value is specified, the forwarding policy ID is used by default.",
		//	  "maxLength": 128,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"transit_router_forward_policy_table_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the forwarding policy. Must start with a letter, number, or Chinese character. Can include letters, numbers, Chinese characters, and the following special characters: period (.), underscore (_), and hyphen (-). Length limit: 1–128 characters. If this parameter is not provided or no value is specified, the forwarding policy ID is used by default.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Transit router instance ID.",
		//	  "type": "string"
		//	}
		"transit_router_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Transit router instance ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Last operation time of the forwarding policy.",
		//	  "type": "string"
		//	}
		"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Last operation time of the forwarding policy.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::TransitRouter::TransitRouterForwardPolicyTable",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::TransitRouter::TransitRouterForwardPolicyTable").WithTerraformTypeName("volcenginecc_transitrouter_transit_router_forward_policy_table")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"creation_time":                            "CreationTime",
		"description":                              "Description",
		"status":                                   "Status",
		"transit_router_attachment_ids":            "TransitRouterAttachmentIds",
		"transit_router_forward_policy_table_id":   "TransitRouterForwardPolicyTableId",
		"transit_router_forward_policy_table_name": "TransitRouterForwardPolicyTableName",
		"transit_router_id":                        "TransitRouterId",
		"update_time":                              "UpdateTime",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
