// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package transitrouter

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_transitrouter_transit_router_traffic_qos_queue_entry", transitRouterTrafficQosQueueEntryResource)
}

// transitRouterTrafficQosQueueEntryResource returns the Terraform volcenginecc_transitrouter_transit_router_traffic_qos_queue_entry resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::TransitRouter::TransitRouterTrafficQosQueueEntry resource.
func transitRouterTrafficQosQueueEntryResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: BandwidthPercent
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Bandwidth percentage allocated to the flow queue entry. Value range: 0 to 100.",
		//	  "maximum": 100,
		//	  "minimum": 0,
		//	  "type": "integer"
		//	}
		"bandwidth_percent": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Bandwidth percentage allocated to the flow queue entry. Value range: 0 to 100.",
			Optional:    true,
			Computed:    true,
			Validators: []validator.Int64{ /*START VALIDATORS*/
				int64validator.Between(0, 100),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: CreationTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation time of the flow queue entry.",
		//	  "type": "string"
		//	}
		"creation_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation time of the flow queue entry.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Description of the flow queue entry. Must start with a letter, number, or Chinese character. Can contain letters, numbers, Chinese characters, and the following special characters: English comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。). Length: 0 to 255 characters.",
		//	  "maxLength": 255,
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Description of the flow queue entry. Must start with a letter, number, or Chinese character. Can contain letters, numbers, Chinese characters, and the following special characters: English comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。). Length: 0 to 255 characters.",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthAtMost(255),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Dscps
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "List of DSCP values matched by the flow queue entry. Each DSCP value ranges from 0 to 63.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "integer"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"dscps": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.Int64Type,
			Description: "List of DSCP values matched by the flow queue entry. Each DSCP value ranges from 0 to 63.",
			Required:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: IsDefault
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Indicates whether this is the default flow queue entry. true: Yes. false: No.",
		//	  "type": "boolean"
		//	}
		"is_default": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Indicates whether this is the default flow queue entry. true: Yes. false: No.",
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Priority
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Priority of the flow queue entry. Normal: Normal. High: High.",
		//	  "enum": [
		//	    "Normal",
		//	    "High"
		//	  ],
		//	  "type": "string"
		//	}
		"priority": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Priority of the flow queue entry. Normal: Normal. High: High.",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.OneOf(
					"Normal",
					"High",
				),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status of the flow queue entry. Creating: Creating. Deleting: Deleting. Pending: Pending. Available: Available.",
		//	  "enum": [
		//	    "Creating",
		//	    "Deleting",
		//	    "Pending",
		//	    "Available"
		//	  ],
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Status of the flow queue entry. Creating: Creating. Deleting: Deleting. Pending: Pending. Available: Available.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterTrafficQosQueueEntryId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the flow queue entry.",
		//	  "type": "string"
		//	}
		"transit_router_traffic_qos_queue_entry_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the flow queue entry.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterTrafficQosQueueEntryName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the flow queue entry. Must start with a letter, number, or Chinese character. Can contain letters, numbers, Chinese characters, and the following special characters: period (.), underscore (_), and hyphen (-). Length: 1 to 128 characters.",
		//	  "maxLength": 128,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"transit_router_traffic_qos_queue_entry_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the flow queue entry. Must start with a letter, number, or Chinese character. Can contain letters, numbers, Chinese characters, and the following special characters: period (.), underscore (_), and hyphen (-). Length: 1 to 128 characters.",
			Required:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthBetween(1, 128),
			}, /*END VALIDATORS*/
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterTrafficQosQueuePolicyId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the flow queue policy, identifying the flow queue policy to which this entry belongs.",
		//	  "type": "string"
		//	}
		"transit_router_traffic_qos_queue_policy_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the flow queue policy, identifying the flow queue policy to which this entry belongs.",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Most recent update time of the flow queue entry.",
		//	  "type": "string"
		//	}
		"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Most recent update time of the flow queue entry.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Transit router flow queue entry. The flow queue entry defines the mapping between specific DSCP sets and priorities, used to assign matched traffic to the corresponding scheduling queue for differentiated scheduling based on business importance.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::TransitRouter::TransitRouterTrafficQosQueueEntry").WithTerraformTypeName("volcenginecc_transitrouter_transit_router_traffic_qos_queue_entry")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"bandwidth_percent": "BandwidthPercent",
		"creation_time":     "CreationTime",
		"description":       "Description",
		"dscps":             "Dscps",
		"is_default":        "IsDefault",
		"priority":          "Priority",
		"status":            "Status",
		"transit_router_traffic_qos_queue_entry_id":   "TransitRouterTrafficQosQueueEntryId",
		"transit_router_traffic_qos_queue_entry_name": "TransitRouterTrafficQosQueueEntryName",
		"transit_router_traffic_qos_queue_policy_id":  "TransitRouterTrafficQosQueuePolicyId",
		"update_time": "UpdateTime",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/TransitRouterTrafficQosQueueEntryId",
		"/properties/Status",
		"/properties/IsDefault",
		"/properties/CreationTime",
		"/properties/UpdateTime",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/TransitRouterTrafficQosQueuePolicyId",
		"/properties/Dscps",
		"/properties/Priority",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
