// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package transitrouter

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_transitrouter_transit_router_traffic_qos_marking_policy", transitRouterTrafficQosMarkingPolicyResource)
}

// transitRouterTrafficQosMarkingPolicyResource returns the Terraform volcenginecc_transitrouter_transit_router_traffic_qos_marking_policy resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::TransitRouter::TransitRouterTrafficQosMarkingPolicy resource.
func transitRouterTrafficQosMarkingPolicyResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CreationTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation time of the flow marking policy.",
		//	  "type": "string"
		//	}
		"creation_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation time of the flow marking policy.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Description of the flow marking policy. Must start with a letter, number, or Chinese character. Can contain letters, numbers, Chinese characters, and the following special characters: comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。). Length limit: 0–255 characters.",
		//	  "maxLength": 255,
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Description of the flow marking policy. Must start with a letter, number, or Chinese character. Can contain letters, numbers, Chinese characters, and the following special characters: comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。). Length limit: 0–255 characters.",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthAtMost(255),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status of the flow marking policy. Creating: being created. Deleting: being deleted. Pending: being configured. Available: available.",
		//	  "enum": [
		//	    "Creating",
		//	    "Deleting",
		//	    "Pending",
		//	    "Available"
		//	  ],
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Status of the flow marking policy. Creating: being created. Deleting: being deleted. Pending: being configured. Available: available.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Transit router instance ID.",
		//	  "type": "string"
		//	}
		"transit_router_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Transit router instance ID.",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterTrafficQosMarkingPolicyId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Flow marking policy ID.",
		//	  "type": "string"
		//	}
		"transit_router_traffic_qos_marking_policy_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Flow marking policy ID.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TransitRouterTrafficQosMarkingPolicyName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the flow marking policy. Must start with a letter, number, or Chinese character. Can contain letters, numbers, Chinese characters, and the following special characters: period (.), underscore (_), and hyphen (-). Length limit: 1–128 characters. If this parameter is not provided or no value is passed, the default is the flow marking policy ID.",
		//	  "maxLength": 128,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"transit_router_traffic_qos_marking_policy_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the flow marking policy. Must start with a letter, number, or Chinese character. Can contain letters, numbers, Chinese characters, and the following special characters: period (.), underscore (_), and hyphen (-). Length limit: 1–128 characters. If this parameter is not provided or no value is passed, the default is the flow marking policy ID.",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthBetween(1, 128),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Last update time of the flow marking policy.",
		//	  "type": "string"
		//	}
		"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Last update time of the flow marking policy.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Transit router flow marking policy. The flow marking policy is used to match traffic forwarded by the transit router to specified scheduling queues, enabling differentiated scheduling based on business importance.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::TransitRouter::TransitRouterTrafficQosMarkingPolicy").WithTerraformTypeName("volcenginecc_transitrouter_transit_router_traffic_qos_marking_policy")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"creation_time":     "CreationTime",
		"description":       "Description",
		"status":            "Status",
		"transit_router_id": "TransitRouterId",
		"transit_router_traffic_qos_marking_policy_id":   "TransitRouterTrafficQosMarkingPolicyId",
		"transit_router_traffic_qos_marking_policy_name": "TransitRouterTrafficQosMarkingPolicyName",
		"update_time": "UpdateTime",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/TransitRouterTrafficQosMarkingPolicyId",
		"/properties/Status",
		"/properties/CreationTime",
		"/properties/UpdateTime",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/TransitRouterId",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
