// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package transitrouter_test

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/acctest"
)

func TestAccVolcengineTransitRouterTransitRouterTrafficQosMarkingEntryDataSource_basic(t *testing.T) {
	td := acctest.NewTestData(t, "Volcengine::TransitRouter::TransitRouterTrafficQosMarkingEntry", "volcenginecc_transitrouter_transit_router_traffic_qos_marking_entry", "test")

	td.DataSourceTest(t, []resource.TestStep{
		{
			Config:      td.EmptyDataSourceConfig(),
			ExpectError: regexp.MustCompile("Missing required argument"),
		},
	})
}

func TestAccVolcengineTransitRouterTransitRouterTrafficQosMarkingEntryDataSource_NonExistent(t *testing.T) {
	td := acctest.NewTestData(t, "Volcengine::TransitRouter::TransitRouterTrafficQosMarkingEntry", "volcenginecc_transitrouter_transit_router_traffic_qos_marking_entry", "test")

	td.DataSourceTest(t, []resource.TestStep{
		{
			Config:      td.DataSourceWithNonExistentIDConfig(),
			ExpectError: regexp.MustCompile("Not Found"),
		},
	})
}
