// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package kafka_test

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/acctest"
)

func TestAccVolcengineKafkaACLDataSource_basic(t *testing.T) {
	td := acctest.NewTestData(t, "Volcengine::Kafka::ACL", "volcenginecc_kafka_acl", "test")

	td.DataSourceTest(t, []resource.TestStep{
		{
			Config:      td.EmptyDataSourceConfig(),
			ExpectError: regexp.MustCompile("Missing required argument"),
		},
	})
}

func TestAccVolcengineKafkaACLDataSource_NonExistent(t *testing.T) {
	td := acctest.NewTestData(t, "Volcengine::Kafka::ACL", "volcenginecc_kafka_acl", "test")

	td.DataSourceTest(t, []resource.TestStep{
		{
			Config:      td.DataSourceWithNonExistentIDConfig(),
			ExpectError: regexp.MustCompile("Not Found"),
		},
	})
}
