// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package vpc

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_vpc_ip_pool", ipPoolResource)
}

// ipPoolResource returns the Terraform volcenginecc_vpc_ip_pool resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::VPC::IpPool resource.
func ipPoolResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AddressSource
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Address source.",
		//	  "type": "string"
		//	}
		"address_source": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Address source.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: BusinessStatus
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Whether the IP address pool is locked. Normal: Normal. FinancialLocked: Financially locked.",
		//	  "type": "string"
		//	}
		"business_status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Whether the IP address pool is locked. Normal: Normal. FinancialLocked: Financially locked.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: CidrBlock
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Example: 101.0.XX.XX/24, IP address range. Only IPv4 address ranges are supported and cannot start with 0. Mask range: 23–30. Note: Only one of CidrBlock or CidrMask can be configured.",
		//	  "type": "string"
		//	}
		"cidr_block": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Example: 101.0.XX.XX/24, IP address range. Only IPv4 address ranges are supported and cannot start with 0. Mask range: 23–30. Note: Only one of CidrBlock or CidrMask can be configured.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
			// CidrBlock is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: CidrBlocks
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IP range information in the IP address pool.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"cidr_blocks": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "IP range information in the IP address pool.",
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: CidrMask
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IP address range mask. Range: 24–28. After entering the mask, the IP address range will be automatically assigned. Note: Only one of CidrBlock or CidrMask can be configured.",
		//	  "type": "integer"
		//	}
		"cidr_mask": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "IP address range mask. Range: 24–28. After entering the mask, the IP address range will be automatically assigned. Note: Only one of CidrBlock or CidrMask can be configured.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
				int64planmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
			// CidrMask is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: CreationTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation time of the IP address pool.",
		//	  "type": "string"
		//	}
		"creation_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation time of the IP address pool.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: DeletedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Resource reclaim time. This parameter is returned only when the resource is shut down due to overdue payment.",
		//	  "type": "string"
		//	}
		"deleted_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Resource reclaim time. This parameter is returned only when the resource is shut down due to overdue payment.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Description of the IP address pool.",
		//	  "maxLength": 255,
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Description of the IP address pool.",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthAtMost(255),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ISP
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Line type. Valid values: BGP (multi-line), ChinaMobile (China Mobile static single line), ChinaTelecom (China Telecom static single line), ChinaUnicom (China Unicom static single line), SingleLine_BGP (BGP single line), Premium_BGP (Premium BGP), Fusion_BGP (Fusion BGP), ChinaMobile_Value (China Mobile Value static single line), ChinaUnicom_Value (China Unicom Value static single line), ChinaTelecom_Value (China Telecom Value static single line).",
		//	  "type": "string"
		//	}
		"isp": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Line type. Valid values: BGP (multi-line), ChinaMobile (China Mobile static single line), ChinaTelecom (China Telecom static single line), ChinaUnicom (China Unicom static single line), SingleLine_BGP (BGP single line), Premium_BGP (Premium BGP), Fusion_BGP (Fusion BGP), ChinaMobile_Value (China Mobile Value static single line), ChinaUnicom_Value (China Unicom Value static single line), ChinaTelecom_Value (China Telecom Value static single line).",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: IpAddressPoolId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the IP address pool.",
		//	  "type": "string"
		//	}
		"ip_address_pool_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the IP address pool.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Name
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the IP address pool.",
		//	  "maxLength": 128,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the IP address pool.",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthBetween(1, 128),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: OverdueTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Resource freeze time. This parameter is returned only when the resource is frozen due to overdue payment.",
		//	  "type": "string"
		//	}
		"overdue_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Resource freeze time. This parameter is returned only when the resource is frozen due to overdue payment.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the project to which the IP address pool belongs.",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the project to which the IP address pool belongs.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SpecificEgress
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Specific egress.",
		//	  "type": "string"
		//	}
		"specific_egress": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Specific egress.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status of the IP address pool. Creating: Creating. Available: Available. Deleting: Deleting. Pending: In configuration.",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Status of the IP address pool. Creating: Creating. Available: Available. Deleting: Deleting. Pending: In configuration.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Tag information of the IP address pool.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Tag.",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Tag key.",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Tag value.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag key.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseNonNullStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag value.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseNonNullStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Tag information of the IP address pool.\n Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TotalIpCount
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Total number of IP addresses contained in the IP address pool.",
		//	  "type": "integer"
		//	}
		"total_ip_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Total number of IP addresses contained in the IP address pool.",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Update time of the IP address pool.",
		//	  "type": "string"
		//	}
		"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Update time of the IP address pool.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: UsedIpCount
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Number of IP addresses allocated as EIP in the IP address pool.",
		//	  "type": "integer"
		//	}
		"used_ip_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Number of IP addresses allocated as EIP in the IP address pool.",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "IP address pool resources.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::VPC::IpPool").WithTerraformTypeName("volcenginecc_vpc_ip_pool")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"address_source":     "AddressSource",
		"business_status":    "BusinessStatus",
		"cidr_block":         "CidrBlock",
		"cidr_blocks":        "CidrBlocks",
		"cidr_mask":          "CidrMask",
		"creation_time":      "CreationTime",
		"deleted_time":       "DeletedTime",
		"description":        "Description",
		"ip_address_pool_id": "IpAddressPoolId",
		"isp":                "ISP",
		"key":                "Key",
		"name":               "Name",
		"overdue_time":       "OverdueTime",
		"project_name":       "ProjectName",
		"specific_egress":    "SpecificEgress",
		"status":             "Status",
		"tags":               "Tags",
		"total_ip_count":     "TotalIpCount",
		"update_time":        "UpdateTime",
		"used_ip_count":      "UsedIpCount",
		"value":              "Value",
	})

	opts = opts.WithWriteOnlyPropertyPaths([]string{
		"/properties/CidrBlock",
		"/properties/CidrMask",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/IpAddressPoolId",
		"/properties/Status",
		"/properties/UsedIpCount",
		"/properties/TotalIpCount",
		"/properties/CreationTime",
		"/properties/UpdateTime",
		"/properties/OverdueTime",
		"/properties/DeletedTime",
		"/properties/BusinessStatus",
		"/properties/SpecificEgress",
		"/properties/AddressSource",
		"/properties/CidrBlocks",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/ISP",
		"/properties/ProjectName",
		"/properties/CidrBlock",
		"/properties/CidrMask",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
