// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package vpc

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_vpc_ip_pool", ipPoolDataSource)
}

// ipPoolDataSource returns the Terraform volcenginecc_vpc_ip_pool data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::VPC::IpPool resource.
func ipPoolDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AddressSource
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Address source.",
		//	  "type": "string"
		//	}
		"address_source": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Address source.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: BusinessStatus
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Whether the IP address pool is locked. Normal: Normal. FinancialLocked: Financially locked.",
		//	  "type": "string"
		//	}
		"business_status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Whether the IP address pool is locked. Normal: Normal. FinancialLocked: Financially locked.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CidrBlock
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Example: 101.0.XX.XX/24, IP address range. Only IPv4 address ranges are supported and cannot start with 0. Mask range: 23–30. Note: Only one of CidrBlock or CidrMask can be configured.",
		//	  "type": "string"
		//	}
		"cidr_block": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Example: 101.0.XX.XX/24, IP address range. Only IPv4 address ranges are supported and cannot start with 0. Mask range: 23–30. Note: Only one of CidrBlock or CidrMask can be configured.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CidrBlocks
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IP range information in the IP address pool.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"cidr_blocks": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "IP range information in the IP address pool.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CidrMask
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IP address range mask. Range: 24–28. After entering the mask, the IP address range will be automatically assigned. Note: Only one of CidrBlock or CidrMask can be configured.",
		//	  "type": "integer"
		//	}
		"cidr_mask": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "IP address range mask. Range: 24–28. After entering the mask, the IP address range will be automatically assigned. Note: Only one of CidrBlock or CidrMask can be configured.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CreationTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation time of the IP address pool.",
		//	  "type": "string"
		//	}
		"creation_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation time of the IP address pool.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DeletedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Resource reclaim time. This parameter is returned only when the resource is shut down due to overdue payment.",
		//	  "type": "string"
		//	}
		"deleted_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Resource reclaim time. This parameter is returned only when the resource is shut down due to overdue payment.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Description of the IP address pool.",
		//	  "maxLength": 255,
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Description of the IP address pool.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ISP
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Line type. Valid values: BGP (multi-line), ChinaMobile (China Mobile static single line), ChinaTelecom (China Telecom static single line), ChinaUnicom (China Unicom static single line), SingleLine_BGP (BGP single line), Premium_BGP (Premium BGP), Fusion_BGP (Fusion BGP), ChinaMobile_Value (China Mobile Value static single line), ChinaUnicom_Value (China Unicom Value static single line), ChinaTelecom_Value (China Telecom Value static single line).",
		//	  "type": "string"
		//	}
		"isp": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Line type. Valid values: BGP (multi-line), ChinaMobile (China Mobile static single line), ChinaTelecom (China Telecom static single line), ChinaUnicom (China Unicom static single line), SingleLine_BGP (BGP single line), Premium_BGP (Premium BGP), Fusion_BGP (Fusion BGP), ChinaMobile_Value (China Mobile Value static single line), ChinaUnicom_Value (China Unicom Value static single line), ChinaTelecom_Value (China Telecom Value static single line).",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: IpAddressPoolId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the IP address pool.",
		//	  "type": "string"
		//	}
		"ip_address_pool_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the IP address pool.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Name
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the IP address pool.",
		//	  "maxLength": 128,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the IP address pool.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: OverdueTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Resource freeze time. This parameter is returned only when the resource is frozen due to overdue payment.",
		//	  "type": "string"
		//	}
		"overdue_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Resource freeze time. This parameter is returned only when the resource is frozen due to overdue payment.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the project to which the IP address pool belongs.",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the project to which the IP address pool belongs.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SpecificEgress
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Specific egress.",
		//	  "type": "string"
		//	}
		"specific_egress": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Specific egress.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status of the IP address pool. Creating: Creating. Available: Available. Deleting: Deleting. Pending: In configuration.",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Status of the IP address pool. Creating: Creating. Available: Available. Deleting: Deleting. Pending: In configuration.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Tag information of the IP address pool.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Tag.",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Tag key.",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Tag value.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag key.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag value.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Tag information of the IP address pool.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TotalIpCount
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Total number of IP addresses contained in the IP address pool.",
		//	  "type": "integer"
		//	}
		"total_ip_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Total number of IP addresses contained in the IP address pool.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Update time of the IP address pool.",
		//	  "type": "string"
		//	}
		"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Update time of the IP address pool.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UsedIpCount
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Number of IP addresses allocated as EIP in the IP address pool.",
		//	  "type": "integer"
		//	}
		"used_ip_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Number of IP addresses allocated as EIP in the IP address pool.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::VPC::IpPool",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::VPC::IpPool").WithTerraformTypeName("volcenginecc_vpc_ip_pool")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"address_source":     "AddressSource",
		"business_status":    "BusinessStatus",
		"cidr_block":         "CidrBlock",
		"cidr_blocks":        "CidrBlocks",
		"cidr_mask":          "CidrMask",
		"creation_time":      "CreationTime",
		"deleted_time":       "DeletedTime",
		"description":        "Description",
		"ip_address_pool_id": "IpAddressPoolId",
		"isp":                "ISP",
		"key":                "Key",
		"name":               "Name",
		"overdue_time":       "OverdueTime",
		"project_name":       "ProjectName",
		"specific_egress":    "SpecificEgress",
		"status":             "Status",
		"tags":               "Tags",
		"total_ip_count":     "TotalIpCount",
		"update_time":        "UpdateTime",
		"used_ip_count":      "UsedIpCount",
		"value":              "Value",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
