// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package vpc

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_vpc_ip_pool_cidr_block", ipPoolCidrBlockDataSource)
}

// ipPoolCidrBlockDataSource returns the Terraform volcenginecc_vpc_ip_pool_cidr_block data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::VPC::IpPoolCidrBlock resource.
func ipPoolCidrBlockDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CidrBlock
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IP address subnet. Only IPv4 subnets are supported and cannot start with 0; mask value range is 23 to 30. Only one of CidrBlock or CidrMask can be configured during creation.",
		//	  "type": "string"
		//	}
		"cidr_block": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "IP address subnet. Only IPv4 subnets are supported and cannot start with 0; mask value range is 23 to 30. Only one of CidrBlock or CidrMask can be configured during creation.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CidrMask
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IP address subnet mask; value range is 24 to 28. After entering the mask, the IP address subnet will be automatically assigned. Only one of CidrBlock or CidrMask can be configured during creation.",
		//	  "maximum": 28,
		//	  "minimum": 24,
		//	  "type": "integer"
		//	}
		"cidr_mask": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "IP address subnet mask; value range is 24 to 28. After entering the mask, the IP address subnet will be automatically assigned. Only one of CidrBlock or CidrMask can be configured during creation.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CreationTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation time of the IP address pool subnet.",
		//	  "type": "string"
		//	}
		"creation_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation time of the IP address pool subnet.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: IpAddressPoolId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the IP address pool.",
		//	  "type": "string"
		//	}
		"ip_address_pool_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the IP address pool.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status of the IP address pool subnet. Creating: In progress. Available: Available. Deleting: In progress. Pending: Configuring.",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Status of the IP address pool subnet. Creating: In progress. Available: Available. Deleting: In progress. Pending: Configuring.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TotalIpCount
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Total number of IP addresses in the IP address pool.",
		//	  "type": "integer"
		//	}
		"total_ip_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Total number of IP addresses in the IP address pool.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UsedIpCount
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Number of used IP addresses in the IP address pool subnet.",
		//	  "type": "integer"
		//	}
		"used_ip_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Number of used IP addresses in the IP address pool subnet.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::VPC::IpPoolCidrBlock",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::VPC::IpPoolCidrBlock").WithTerraformTypeName("volcenginecc_vpc_ip_pool_cidr_block")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"cidr_block":         "CidrBlock",
		"cidr_mask":          "CidrMask",
		"creation_time":      "CreationTime",
		"ip_address_pool_id": "IpAddressPoolId",
		"status":             "Status",
		"total_ip_count":     "TotalIpCount",
		"used_ip_count":      "UsedIpCount",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
