// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package vpc

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_vpc_ipam", iPAMDataSource)
}

// iPAMDataSource returns the Terraform volcenginecc_vpc_ipam data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::VPC::IPAM resource.
func iPAMDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AccountId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Account ID",
		//	  "type": "string"
		//	}
		"account_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Account ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CreateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation Time",
		//	  "type": "string"
		//	}
		"create_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation Time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DefaultResourceDiscoveryAssociationId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Default Resource Discovery Association ID",
		//	  "type": "string"
		//	}
		"default_resource_discovery_association_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Default Resource Discovery Association ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DefaultResourceDiscoveryId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Default Resource Discovery Instance ID",
		//	  "type": "string"
		//	}
		"default_resource_discovery_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Default Resource Discovery Instance ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Description",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Description",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: IpamId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IPAM ID",
		//	  "type": "string"
		//	}
		"ipam_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "IPAM ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: IpamName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IPAM Name",
		//	  "maxLength": 255,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"ipam_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "IPAM Name",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: IpamRegionId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Region ID",
		//	  "type": "string"
		//	}
		"ipam_region_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Region ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: OperatingRegions
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IPAM Effective Region",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"operating_regions": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "IPAM Effective Region",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: PrivateDefaultScopeId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "System Default Created Private IPAM Scope",
		//	  "type": "string"
		//	}
		"private_default_scope_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "System Default Created Private IPAM Scope",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Project Name",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Project Name",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: PublicDefaultScopeId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "System Default Created Public IPAM Scope",
		//	  "type": "string"
		//	}
		"public_default_scope_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "System Default Created Public IPAM Scope",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ResourceDiscoveryAssociationCount
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Resource Discovery Association Count",
		//	  "type": "integer"
		//	}
		"resource_discovery_association_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Resource Discovery Association Count",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ScopeCount
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IPAM Scope Count",
		//	  "type": "integer"
		//	}
		"scope_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "IPAM Scope Count",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IPAM Status",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "IPAM Status",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IPAM Tag Information",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Tag",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Tag Key",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Tag Value",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag Key",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag Value",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "IPAM Tag Information",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Update Time",
		//	  "type": "string"
		//	}
		"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Update Time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::VPC::IPAM",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::VPC::IPAM").WithTerraformTypeName("volcenginecc_vpc_ipam")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"account_id":  "AccountId",
		"create_time": "CreateTime",
		"default_resource_discovery_association_id": "DefaultResourceDiscoveryAssociationId",
		"default_resource_discovery_id":             "DefaultResourceDiscoveryId",
		"description":                               "Description",
		"ipam_id":                                   "IpamId",
		"ipam_name":                                 "IpamName",
		"ipam_region_id":                            "IpamRegionId",
		"key":                                       "Key",
		"operating_regions":                         "OperatingRegions",
		"private_default_scope_id":                  "PrivateDefaultScopeId",
		"project_name":                              "ProjectName",
		"public_default_scope_id":                   "PublicDefaultScopeId",
		"resource_discovery_association_count":      "ResourceDiscoveryAssociationCount",
		"scope_count":                               "ScopeCount",
		"status":                                    "Status",
		"tags":                                      "Tags",
		"update_time":                               "UpdateTime",
		"value":                                     "Value",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
