// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package vpc

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_vpc_ipam", iPAMResource)
}

// iPAMResource returns the Terraform volcenginecc_vpc_ipam resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::VPC::IPAM resource.
func iPAMResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AccountId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Account ID",
		//	  "type": "string"
		//	}
		"account_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Account ID",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: CreateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation Time",
		//	  "type": "string"
		//	}
		"create_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation Time",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: DefaultResourceDiscoveryAssociationId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Default Resource Discovery Association ID",
		//	  "type": "string"
		//	}
		"default_resource_discovery_association_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Default Resource Discovery Association ID",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: DefaultResourceDiscoveryId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Default Resource Discovery Instance ID",
		//	  "type": "string"
		//	}
		"default_resource_discovery_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Default Resource Discovery Instance ID",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Description",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Description",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: IpamId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IPAM ID",
		//	  "type": "string"
		//	}
		"ipam_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "IPAM ID",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: IpamName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IPAM Name",
		//	  "maxLength": 255,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"ipam_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "IPAM Name",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthBetween(1, 255),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: IpamRegionId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Region ID",
		//	  "type": "string"
		//	}
		"ipam_region_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Region ID",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: OperatingRegions
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IPAM Effective Region",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"operating_regions": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "IPAM Effective Region",
			Required:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: PrivateDefaultScopeId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "System Default Created Private IPAM Scope",
		//	  "type": "string"
		//	}
		"private_default_scope_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "System Default Created Private IPAM Scope",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Project Name",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Project Name",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: PublicDefaultScopeId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "System Default Created Public IPAM Scope",
		//	  "type": "string"
		//	}
		"public_default_scope_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "System Default Created Public IPAM Scope",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ResourceDiscoveryAssociationCount
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Resource Discovery Association Count",
		//	  "type": "integer"
		//	}
		"resource_discovery_association_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Resource Discovery Association Count",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ScopeCount
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IPAM Scope Count",
		//	  "type": "integer"
		//	}
		"scope_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "IPAM Scope Count",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IPAM Status",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "IPAM Status",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IPAM Tag Information",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Tag",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Tag Key",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Tag Value",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag Key",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseNonNullStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag Value",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseNonNullStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "IPAM Tag Information\n Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Update Time",
		//	  "type": "string"
		//	}
		"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Update Time",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "IPAM。",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::VPC::IPAM").WithTerraformTypeName("volcenginecc_vpc_ipam")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"account_id":  "AccountId",
		"create_time": "CreateTime",
		"default_resource_discovery_association_id": "DefaultResourceDiscoveryAssociationId",
		"default_resource_discovery_id":             "DefaultResourceDiscoveryId",
		"description":                               "Description",
		"ipam_id":                                   "IpamId",
		"ipam_name":                                 "IpamName",
		"ipam_region_id":                            "IpamRegionId",
		"key":                                       "Key",
		"operating_regions":                         "OperatingRegions",
		"private_default_scope_id":                  "PrivateDefaultScopeId",
		"project_name":                              "ProjectName",
		"public_default_scope_id":                   "PublicDefaultScopeId",
		"resource_discovery_association_count":      "ResourceDiscoveryAssociationCount",
		"scope_count":                               "ScopeCount",
		"status":                                    "Status",
		"tags":                                      "Tags",
		"update_time":                               "UpdateTime",
		"value":                                     "Value",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/IpamId",
		"/properties/PublicDefaultScopeId",
		"/properties/PrivateDefaultScopeId",
		"/properties/DefaultResourceDiscoveryId",
		"/properties/DefaultResourceDiscoveryAssociationId",
		"/properties/AccountId",
		"/properties/CreateTime",
		"/properties/UpdateTime",
		"/properties/Status",
		"/properties/IpamRegionId",
		"/properties/ScopeCount",
		"/properties/ResourceDiscoveryAssociationCount",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/ProjectName",
		"/properties/OperatingRegions",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
