// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package vmp

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_vmp_integration_task", integrationTaskDataSource)
}

// integrationTaskDataSource returns the Terraform volcenginecc_vmp_integration_task data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::VMP::IntegrationTask resource.
func integrationTaskDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CreateParams
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Integration Task Parameters in JSON Format (provided during creation/update)",
		//	  "type": "string"
		//	}
		"create_params": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Integration Task Parameters in JSON Format (provided during creation/update)",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Enabled
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enable Switch for Integration Task. True means enabled, false means disabled",
		//	  "type": "boolean"
		//	}
		"enabled": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Enable Switch for Integration Task. True means enabled, false means disabled",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Environment
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Integration Task Environment",
		//	  "type": "string"
		//	}
		"environment": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Integration Task Environment",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: IntegrationTaskId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Integration Task Unique Identifier",
		//	  "type": "string"
		//	}
		"integration_task_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Integration Task Unique Identifier",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Name
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Integration Task Name",
		//	  "type": "string"
		//	}
		"name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Integration Task Name",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Project Name to Which Integration Task Belongs",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Project Name to Which Integration Task Belongs",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ReadParams
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Integration Task Parameters in JSON Format (read-only, returned data)",
		//	  "type": "string"
		//	}
		"read_params": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Integration Task Parameters in JSON Format (read-only, returned data)",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Actual Running Status of Integration Task (read-only). Values: Creating, Updating, Active, Disabled, Error, Deleting",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Actual Running Status of Integration Task (read-only). Values: Creating, Updating, Active, Disabled, Error, Deleting",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SubType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Integration Task Subtype",
		//	  "type": "string"
		//	}
		"sub_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Integration Task Subtype",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Integration Task Tag List",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Resource Tag",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Tag Key",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Tag Value",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key",
		//	      "Value"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag Key",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag Value",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Integration Task Tag List",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Type
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Integration Task Type",
		//	  "type": "string"
		//	}
		"type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Integration Task Type",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: VkeClusterId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "VKE Cluster ID Associated with Integration Task",
		//	  "type": "string"
		//	}
		"vke_cluster_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "VKE Cluster ID Associated with Integration Task",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: WorkspaceId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Workspace ID Associated with Integration Task",
		//	  "type": "string"
		//	}
		"workspace_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Workspace ID Associated with Integration Task",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::VMP::IntegrationTask",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::VMP::IntegrationTask").WithTerraformTypeName("volcenginecc_vmp_integration_task")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"create_params":       "CreateParams",
		"enabled":             "Enabled",
		"environment":         "Environment",
		"integration_task_id": "IntegrationTaskId",
		"key":                 "Key",
		"name":                "Name",
		"project_name":        "ProjectName",
		"read_params":         "ReadParams",
		"status":              "Status",
		"sub_type":            "SubType",
		"tags":                "Tags",
		"type":                "Type",
		"value":               "Value",
		"vke_cluster_id":      "VkeClusterId",
		"workspace_id":        "WorkspaceId",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
